### ISSUE TITLE
New 'Media bar'

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-web#151]
Assigned to @argoroots  

We have interviews published in media now, that we can showcase. Asked for a ['media bar' design from Kevin:](https://projects.invisionapp.com/d/main#/console/14853137/322553706/preview) 

Kevin: " I suggest putting it under the news block."
I (Liina) think that the media bar could be present on most pages: landing page, product, news, vision, community. 

Kevin: "I added 4 logos there so Argo can take them."
NB the 'Avatud Eesti fond' logo should be 'Kuku radio' logo instead.
NB there should be a 5th logo: [World Cleanup Day (without date)](https://www.dropbox.com/sh/29mzqde6dip80ob/AACP3DujNAw-6WFvrY4-nqwta/WCD%20logo%20no%20date?dl=0&subfolder_nav_tracking=1)
And the 6th logo [rohelised](https://erakond.ee/eestimaa-rohelised/uldkoosolek-oli-edukas-citizen-os-kaasabil-valiti-kaks-juhti-ja-teised-kogud/)

The logos / links should be clickable I think. 

In English first, then Estonian and then Indonesian left to right in the bar: 

in English: 
[World Cleanup Day](https://www.dropbox.com/sh/29mzqde6dip80ob/AACP3DujNAw-6WFvrY4-nqwta/WCD%20logo%20no%20date?dl=0&subfolder_nav_tracking=1)
[e-Estonia](https://e-estonia.com/e-talks-citizen-os-e-democracy-platform-for-the-citizens-of-the-world/)
[rohelised](https://erakond.ee/eestimaa-rohelised/uldkoosolek-oli-edukas-citizen-os-kaasabil-valiti-kaks-juhti-ja-teised-kogud/#)

In Estonian:
[Kuku radio](https://oef.org.ee/paevakajaline/artikkel/aef-minutid-25-novembril)
[ERR](https://www.err.ee/1001718/margo-loor-eesti-ilma-riigikoguta-kas-esindusdemokraatia-aeg-on-labi)
[Hea Kodanik](https://heakodanik.ee/uudised/kuidas-laheb-citizenos/)
[rohelised](https://erakond.ee/eestimaa-rohelised/uldkoosolek-oli-edukas-citizen-os-kaasabil-valiti-kaks-juhti-ja-teised-kogud/)

Oh and one In Indonesian: 
[ProBintan](https://bintan.batampos.co.id/2020/07/02/dorong-tiap-desa-punya-sistem-pengelolaan-sampah/?__cf_chl_jschl_tk__=e233c034611ddbe316d179a8cd2eb606db322ac9-1608160807-0-AS9xW9vwxWSfiVeBpbwK1LUG5dy3Ec0M7p5kNBLoYvbnEI8qaYeApAroQbWEpRerbLgKFAmptb2-lQUKVw60pA-B2p6WkaQAB2BZZUejI8SaW3yV4XWlE4orvi1KxXN2vVQhWi6uYFVYndhB9FLJ_euYNo_8g6kmkmmfvmqnXo_-aZ7RGoInf7zqWyIu4_7oyp6a7S3ABJZixedlH-42xvQZiOzTIVYgSrwRRH9kpB1JR_AZ1-U8lvi6Td-0pVTkjjuuAREXgRbO20JOrPAHKlbeYWrUA9IorHX-NeXE2AKcZgRKODkZdteHRx24KQgtninqrjjqicLvUxx-ZJpUn0EY-zf1t2P6Bi_oWKZJOGoZjc-cY9go31jkIxtwB3K3jQ)

**Comment by liinaguiter** [comment]
@kevincrepin, we also need the '[Kuku radio](https://kuku.postimees.ee/)' logo, '[World Cleanup Day](https://www.dropbox.com/sh/29mzqde6dip80ob/AACP3DujNAw-6WFvrY4-nqwta/WCD%20logo%20no%20date?dl=0&subfolder_nav_tracking=1)' logo (without date), '[rohelised](https://erakond.ee/)' logo and '[ProBintan]'(https://bintan.batampos.co.id/2020/07/02/dorong-tiap-desa-punya-sistem-pengelolaan-sampah/?__cf_chl_jschl_tk__=6f761ac7cdfc5c6b061af593531f30e83921947c-1608215669-0-ATs_0yE_7fX-HD3jDbapeHH29EGWjAvKVJH6dvWR7NyJcX5VxrG4LGaLSIYxuvqSsaBDsoDXvLFxKJCbAYIoScBesvr_QOx58MssrzNgaQhKTEFhwNsyfifnAsrkh2zWcVSfgRxilOeocjdmW2LSXDWiNym0lIjCV-b2GttUJ-nXSRjM8Y6hKxibCc4N-yMdj7WZ-haTf3fJyvwAHtcDOOnZDuHggJWMte7_6VmJXxs1-tkKHGytu3HZqs5xCu86vWe-N2Fgl0XqKPJ-fc9V7JTNpC2zx5xpxDCAkQl1OEJNulu8yTe2CdQue3MZqGXhfHFhng2wuyDu4qIkv1pzvTAEvgXr8jyBWJlCym2aqUGOufpvc898dbDDeWGg4fxSGg) logo

**Comment by kevincrepin** [comment]
@argoroots Can you try these? They have the same height but spacing between them should still be done in code. Seems normal I think? :D 

[media_images.zip](https://github.com/citizenos/citizenos-web/files/5797208/media_images.zip)
