### ISSUE TITLE
Enhancement: Please make 'Latest news' block viewable in all languages.

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-web#165]
Please make 'Latest news' block viewable in all languages. Actually bring back, as they originally were viewable in all languges. 

The justification earlier was that it is strange to see text in another language all of a sudden. But now we have the Indonesian website translated only partially, so it is justified to also be able to see the 'News' section, which is very important for our users to notice.

<img width="1224" alt="Screenshot 2021-03-31 at 18 16 02" src="https://user-images.githubusercontent.com/34899902/113168903-c3cc1100-924d-11eb-84f2-9da024d816de.png">

**Comment by argoroots** [comment]
Done!
