### ISSUE TITLE
Enhancement: Give webinar landing page template proper website header and footer

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-web#166]
**What is the problem?**
The webinar landing page template needs a proper website header and footer.

At the current header, replace COS logo with website header.
At the footer, replace COS logo and slogan with footer. 

https://projects.invisionapp.com/d/main#/console/14853137/352164402/preview

At the moment, webinar landing page template is used for 
1. et/e-kaasamiskoolitus
2. /pyln

**Comment by argoroots** [comment]
Done!
