### ISSUE TITLE
Enhancement: 'request a demo' email address

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-web#191]
We're getting a 'Request a demo' button on the website and the question is, which email should the request land on. 

If we use info@citizenos.com, which is an alias to Margo, Anett and Liina, then if we put on 'out of office' reply to our personal email, then the demo request gets it as well, which is not good. 

If we use support@citizenos.com, then the demo request get an automatic reply, which is directed towards bugs. 

So option: we create a new email for demo requests (but that email needs to be checked separately then). 
We use info@citizenos.com, and live with the fact that sometimes the out-of-office reply is on. Someone will always answer though. 
Or we change the support@citizenos.com automatic reply. Right now it is the following: 

Dear CitizenOS user,

We have received the e-mail you sent to support@citizenos.com. Critical issues and bugs will be dealt with immediately. Development requests, non-critical bugs and other enquiries will be answered within two working days.

Thank you for using CitizenOS!
--------------------------------------------------------------------------------------------------------------------------------------

Hea CitizenOS kasutaja,

Saime kätte teie saadetud e-kirja. Kriitiliste vigadega tegeleme koheselt. Arendussoovidele, mittekriitilistele veateadetele ja teistele päringutele vastame kahe tööpäeva jooksul.

Aitäh, et kasutate CitizenOSi oma otsuste tegemiseks!

**Comment by BeccaMelhuish** [comment]
@liinaguiter what about if there was a new email for demo requests (with a specific demo related auto reply), but all of those emails got auto-forwarded to the support email? Then only the support email would actually need to be checked.. Does that work?

**Comment by liinaguiter** [comment]
After offline discussions, decided to keep on using info@citizenos.com for now.
