### ISSUE TITLE
BUG: Product page bottom image and counter off-center

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-web#211]
Product page: https://citizenos.com/product/ bottom image and counter are off-center. Please center. Thank you!

![Screenshot 2021-07-20 at 13 57 48](https://user-images.githubusercontent.com/34899902/126313631-f130c4d8-2dc7-4754-b9de-5d60ca5be1bf.png)

**Comment by oksks** [comment]
@argoroots - this seems to still be the case.

**Comment by argoroots** [comment]
Done
