### ISSUE TITLE
Text-based page redesign

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#278]
**Current state:** 
Our website currently looks quite empty, with huge images, lots of air around them, and very (VERY) little text. 
And where we do have some text-heavy pages on our website, they look weirdly put together - they have a huge empty blue block (that takes half the space) on the left-hand side, and loads of text on the right-hand side. Probably they were designed differently, but something went a bit off track along the way. 

Few examples: 
- https://citizenos.com/get-involved/
- https://citizenos.com/about-us/
- https://citizenos.com/contact/

We have quite a few such pages, which will need improvement + we'll be creating new similar ones with more copy than on these pages.

**Request:**
We'd like to request a new design for a text-centered page: maybe a small intro/summary at the top, a considerable amount of copy (structured somehow?), maybe a couple of small graphic/images to illustrate and enliven the content - I'll leave that to you @kevincrepin, to decide, what's necessary :)

Also, would be great to have an option to add a section of 3-4 images with quotes where necessary (for example, a few quotes/user stories from our volunteers with their photos) 

==================
@kevincrepin could you please kindly create such a template (or a few variations) to suit the pages mentioned above + future ones? 

Is Wednesday, March 2, OK for a deadline? Thank you in advance 🙏 
(cc @anettlinno)

**Comment by oksks** [comment]
@kevincrepin asked:
_Do you by any chance already have some of the new copy so I can have an idea of how much there would/could be?
For the existing pages the amount of text stays?_

We don't have any new copy yet, but it could be something a'la on this page: https://citizenos.com/news/my-volunteer-experience-sara-sinha. 
This one's also a lengthy one: https://citizenos.com/product/features/

For the above-mentioned existing pages, the amount of text might expand - definitely in case of About Us page. Contact page will stay the same, Get Involved probably to stay more or less the same, too.

Some more examples:
https://citizenos.com/legal/ is also one of the blue-block pages that will move to the new template.
https://citizenos.com/careers/

**Comment by kevincrepin** [comment]
@oksks I made some templates for different amounts of content. Of course it's always better to have content to design, but there should be some flexibility here. of course some have very little content, which needs filler to give a reason why it's a page. I added some photos here and there, would be nice to have some more.

You can view the templates (desktop + mobile) here: https://www.figma.com/file/eHBSunqUv10fMcWmiEEXiv/Website?node-id=0%3A2160

**Comment by oksks** [comment]
Thank you @kevincrepin, I really like what you did there with the small-medium-big division by content amount, and different blocks allow for easy plug-and-play to suit any particular need. I think you also hit the right note on the text vs. copy vs. "air" proportions we had in mind.
We'll go over it with @anettlinno and come back if anything else is needed :) Thanks!
