### ISSUE TITLE
TASK:  "Help request" form - email address needs to be compulsory

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#287]
**What needs to be done?**
Currently, adding an email address to your help request is optional. It should be compulsory, as we have to have contact details to be able to respond to users or get more details from them.

**Location**
https://citizenos.com/help/request

**Deadline**
By April 5, 2022

**Comment by argoroots** [comment]
Done

**Comment by oksks** [comment]
@argoroots - I was still able to send through a help request without adding an email address 🤔 
Have you tested it?

**Comment by argoroots** [comment]
"Works on my machine". Ehk on sul leht cachetud. Tee refresh.

**Comment by oksks** [comment]
I did, tried both Chrome and Safari. I get no feedback my message didn't go through. 
What is the programmed behaviour? Will the "Send" button be disabled, or user would get a pop-up message, or the email field would become red?

**Comment by oksks** [comment]
@argoroots

**Comment by argoroots** [comment]
done
