### ISSUE TITLE
TASK: Event template improvements

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#296]
**What needs to be done?**
We've reviewed the event page template, and found a few changes are needed - could you please make them a part of the style sheet, so any future events would have the same style?

- [x] - **Add space between headers and the following text:**
![image](https://user-images.githubusercontent.com/34126353/163773325-89aa516c-d6e9-4bc2-8ae6-d697a439b438.png)

- [x] - **Make the right-hand summary box's headlines a smaller size by default**
It should fit into the box in one line.
![Screenshot 2022-04-18 at 10 48 20](https://user-images.githubusercontent.com/34126353/163775335-fc0bbe13-22d1-468b-973f-35a1cf8f353e.png)

- [x] - **"Registration Deadline" additional info point design to summary box**
It wasn't a part of the style initially, but needs to become a default part of the template. Please make it as a separate smaller headline, and the registration deadline itself would be on a separate row and have an alarm bell icon - lmk if you need Kevin's help for that.
![Screenshot 2022-04-18 at 10 34 45](https://user-images.githubusercontent.com/34126353/163773751-4b2257c1-4879-4c35-8172-0f2bce64bb3d.png)

- [x] - **Add a "Price" info point to summary box**
Please implement two solutions: 
- right where the date and time are displayed, with a minimal "coins" icon to signify cost.
- make an additional headline "Price" and allow for text info to be added below, as with "Registration deadline" item.

- [x] - **Make sure agenda section stands out from the rest of the text**
Please add "event agenda" to style sheet and make it light grey to avoid having the whole long page in the same text. Should be the same grey, as "Latest news" section on the [front page](https://citizenos.com/). 

- [x] - **Make sure event page images are displayed correctly on mobile**

![278464457_400317668291535_5160146682390594602_n](https://user-images.githubusercontent.com/34126353/163776373-1fc9a427-98ad-4e08-931f-19cb529989af.jpeg)

- [x] - **"Facilitators" -  additional info point design**
Please add a separate style for facilitators - their image, cut into a circle, with a name, role and descriptive text blocks. Each facilitator's box should be separated from the following one visually, maybe by adding a shadow under each box, or something similar.

![facilitator](https://user-images.githubusercontent.com/34126353/163778394-5c055897-92b7-43dc-87d4-b7d2a8330772.png)

- [x] - Add a "Sign up" button to the mobile view
If the event page is viewed from a smaller screen, the Sign Up button is displayed at the bottom of a long page. Please display an additional "Sign up" button right under the main headline.
![signup](https://user-images.githubusercontent.com/34126353/163779260-6088cbd0-1e52-4c8b-8530-61289b3288c4.jpeg)

- [ ] - Add a "Contact us" style box
At the bottom of the page, please add a "For any enquiries, please email sara@citizenos.com" box. The text should be centered, email should be a link.

- [x] - Please add an option to turn text into a button in any part of the body text, like here:
![Screenshot 2022-09-27 at 20 15 02](https://user-images.githubusercontent.com/34126353/192592802-f317c782-3a69-41a9-8ecf-0073e92370f2.png)
I think we're safe to use the same 3 button designs from the V2 template pages on [Figma](https://www.figma.com/file/eHBSunqUv10fMcWmiEEXiv/Website?node-id=0%3A2160):
<img width="727" alt="Screenshot 2022-09-27 at 22 21 03" src="https://user-images.githubusercontent.com/34126353/192616867-ee500ff7-1bf0-4771-89e6-ac99bc283035.png">
Just please make sure I can choose which design to use every time I create a button.

----

- [ ] - Please allow to fill/remove background colour for various sections of text. Right now, we have only planned this for "agenda", but it's needed throughout the event page. Please allow for the background colour to be changeable, but default to be grey.

----
- [x] - Please make the graphic in the body text smaller on bigger screens - not sure what the max size should be, pls define it yourself.
----
- [ ] - Uploaded header image doesn't fit the screen - please make sure the header image always fits the width of the screen.
----
- [x] - Sponsor logos - I've added 3 images at the bottom of the DDA page, which don't show up for some reason. We need a block for 3-5 sponsor logos as well.
`          ![Active Citizens Fund](/assets/images/events/dda/1. Active-citizens-fund@4x.png){ .img-fluid }
            ![AEF logo](public/assets/images/events/dda/2. AEF_logo_mv.jpg){ .img-fluid }
            ![Vabaühenduste Liidu Logo](public/assets/images/events/dda/3. vabauhenduste-liidu-logo-800.png){ .img-fluid }`

----

**Location**
https://citizenos.com/democracy-defenders-bootcamp
https://citizenos.com/civic-hackathon/

**Deadline**
10am Friday, April 22.

**Comment by oksks** [comment]
@argoroots please kindly make sure everything works in mobile view as well! :) Thanks.

**Comment by oksks** [comment]
Hi @argoroots, it seems that the last item on the list still needs addressing.

**Comment by oksks** [comment]
@argoroots 
1)  "Registration Deadline" additional info point design to summary box - this point still isn't done, albeit marked as such
2)  "Make sure agenda section stands out from the rest of the text" - marked as done - pls provide instructions on how to implement this part
3)  "Add a "Contact us" style box" - this point isn't yet done

These are all needed urgently, please action ASAP.

**Comment by oksks** [comment]
After trying to use the template further, I've added a few more points to the list, that need to be implemented - some found bugs, some additional features.

**Comment by argoroots** [comment]
ETA: 10.10.2022

**Comment by argoroots** [comment]
@oksks for buttons add { .btn .btn-primary } or { .btn .btn-donate } to end of link for blue and pink buttons. It's not easy to bring over new design buttons to old page without breaking old buttons and will not look good if some buttons on page are different than others.

**Comment by oksks** [comment]
Thanks. Relevant things have been implemented for DDA, will make a new ticket if we need anything else. Closing.
