### ISSUE TITLE
Frontpage redesign - UX review

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#298]
**Background info:**

We've decided to revamp the current website - reshuffle the structure and add a lot more content to all sections, as it's currently bare bones. We feel, that design should also be a bit more condensed, not as image-centered as it is now.

We're starting with the Frontpage, moving on to the next big sections later (Product page is next in line). We think it makes sense to make the landing page SaaS-centered, as that's currently our main value proposition and we need to keep users focused on that - current page has all sorts of bits and bobs and leaves the visitor baffled as to what we're actually about. 
Additionally, top navigation will provide overview of other main areas at all times.

Here's the [structure of the frontpage](https://docs.google.com/document/d/1WsNz7iRHFnov3NVI9z9L_53h8Wt9Fa95LcSGeWtqYYM/edit), that I've compiled - a bunch of screenshots - "chunks" from other pages (it's not stealing, it's getting inspired :D) with layouts that I think could work for the purpose, and headline above each chunk describes, what COS-based information it would contain. 

**Request:**

@kevincrepin, could you please take a look at the document as a UX expert, and let us know: 
1) Whether that makes sense at all? As a first-time visitor on COS page. 
Maybe some chunks need reshuffling? Maybe something's missing, for the experience to be cohesive? Maybe all this doesn't make sense at all and should be approached differently?
2) Do the chunks look OK if we were to reuse them more or less exactly as they are?

**Location**
https://citizenos.com/

**Deadline**
Is a week ok? 1-2 hours for UX review are signed off by Anett.

**Comment by kevincrepin** [comment]
Reviewed the structure and for me it's nice. A lot more informative than the current information. Creating this so Argo can take it into dev will take about 4 hrs, using the new templates as a basis.

**Comment by oksks** [comment]
Thank you @kevincrepin! @anettlinno, what do you say? Can we go ahead with this?

**Comment by anettlinno** [comment]
@oksks @kevincrepin yes, let´s do it :)

**Comment by kevincrepin** [comment]
I will find some time next week to do this!

**Comment by oksks** [comment]
Thanks @kevincrepin! Wow, this already looks miles better, cleaner and more "now", than the current one (jaysus, I'm shocked to realize how quickly and seamlessly design ages:( )

I agree 100% on illustrations vs photos, I know it's really hard to find new photos that'd work with existing ones.

Illustrations do look friendly, but tbh seem a bit too kindergarteny/children-book'y to me. But maybe, if we were to tone down the colours and patterns on characters' clothes, they might work. Do you think we could try adjusting one illustration and seeing the before and after to get a bit of understanding, of how they would look when COS'ified? 

Thank you! Super excited for all this!!

**Comment by oksks** [comment]
Also @kevincrepin I just thought to confirm, that out app redesign and web redesign styles are aligned, right? Please let me know if something I'm requesting for web is totally off the course, as I'm a total n00b and have no idea what I'm doing most of the time :P

**Comment by kevincrepin** [comment]
Yes, the web and app will align :)

We have some different illustration packs that we found (and are affordable), maybe there's one that has your preference? We could use it as a basis and add more specific elements ourselves.

We're leaning towards positive and fun, but not childish:

1.
https://www.getillustrations.com/illustration-pack/surrealism-hand-drawn-vector-illustration-pack

2.
https://www.getillustrations.com/illustration-pack/gusto-vector-illustrations

3.
https://www.getillustrations.com/illustration-pack/crayon-illustrations-for-ui-interface

**Comment by oksks** [comment]
Thank you @kevincrepin! 
We (me & @anettlinno) have reviewed the packs and - honestly - found it super hard to imagine these styles on our website, within the new design :D I'm also having trouble imagining, how these illustrations would be made to fit the context of a particular "chunk" - but that's your work and we trust you :)

SO! Style-wise, we like the first pack (surrealism) the most.
However, @anettlinno also thought to ask you about another idea: as you might've seen, the backwall in our Telliskivi office is covered with a custom-made mural by the artist https://www.maarisoekov.ee/. It has a lot of characters engaging in a plethora of different activities, that are close to the COS's heart:

![Mural on the wall (1)](https://user-images.githubusercontent.com/34126353/166924608-52747208-649a-44ab-a0e9-05f1535fed4d.jpg)

Sometime ago, when we were thinking of starting redesigning our web, we thought that maybe we could digitalize these characters and use them as illustrations. But now I understand, that it's a lot of work, and style of the artist is of a huge importance here. I'll ask nevertheless - do you think it would be feasible to create a similar illustration pack ourselves? With the characters from mural? What would be the cost & time required?
Maari is happy to digitalize them if that makes sense.

Another question @anettlinno had - what's the density of illustrations on the page, you would say? I mean, would it be 1-2 illustrations per page or more?
Thanks!

**Comment by kevincrepin** [comment]
Obviously if we could use, reuse or make additional illustrations like the mural that would be cool. But yes it would of course also take time & cost. Bit hard to say how much exactly because illustration work isn't our expertise. I would rather then that the artist herself makes an offer for this...

I think we could/would have 3 illustrations per page max... On longer pages more than on shorter pages and maybe on some pages there aren't any.

**Comment by BeccaMelhuish** [comment]
Hi @kevincrepin! Me @anettlinno and @oksks just had a call re the home page design and here are a few updates for you :) 

- We'd like the new design to look visually quite similar to the current design. For two reasons: (1) As we are only changing one page at a time, we want the existing pages to fit in nice and smoothly with the new page(s) when they are developed, so that it all feels nice an seamless moving between them. (2) For branding consistency and brand strength, we'd like the COS brand to come out more on the new pages, as currently it is only the brand font Noto Sans and the logo that mark it out as a COS page. The other elements of the brand -- i.e. the blue gradient buttons, the gradient circles, the grey pattern, the brand colours -- aren't currently present (though we realise the idea is probably to bring these brand elements in more with the use of illustrations). It doesn't need to be so heavy/present as it is on the existing site (circles everywhere) but it should be there enough so that it is recognisable as a COS page (for anyone who has seen COS designs elsewhere). There also seems to be a new font in the design too if I'm not mistaken ("Let's start a"), which isn't the Noto Sans one. 

- We were hoping you could adjust the design a bit for the last 4 sections, so that it's not so repetitive with the "4 grids" layout one after another (in 4 sections, though the third one is slightly different). It's not so pleasing on the eye as the top few sections which are nice and varied, and also feels a bit overwhelming - lots of info all crammed in. (We realise we might need to rethink the content here, to make sure it's not too much of an overload / not too repetitive. But just feedback for now, and perhaps can be considered when the content is shared with you).
![image](https://user-images.githubusercontent.com/61320526/168296760-ac4d7772-56a6-4706-9cbd-78db3fb511ae.png)

- We decided not to commission the mural inspired creatures illustrations, but will stick with purchasing an illustration pack. We'll browse a few options on the getillustrations website you shared and let you know when we hopefully find something that feels right :)

**Comment by oksks** [comment]
@kevincrepin, in addition to what Becca asked for above, here are a few more observations me and Anett have arrived at:

- First chunk will have 2 CTA buttons: 1) Watch demo (leads to video), and 2) Use platform (instead of just one button)
- Top navigation - could it be a bit more separated from the rest of the page? So it would be a bit better visible. Especially the Use Platform button, is gets kinda lost in all the colours and imagery and should be a bit more prominent.
- Bottom of the page - chunk with a black background - could we please make it another colour, not as dark?
- "What motivates us" chunk - having 4 quotes visible at once is maybe too much - perhaps make it a slider, to display just one user quote at a time? One quote would be 3 sentences max.

Thanks! Copy has just been finalized by @anettlinno - you can find it [here](https://docs.google.com/document/d/1XtuDMXcpCyyFRR4DTFtBwWtxqIlzd9moQxK7XPAX0QY/edit?usp=sharing).

**Comment by anettlinno** [comment]
Here are some style examples that I feel are suitable for us: 
No #1: https://drawkit.com/product/startups-tech-illustrations 
No #2: https://drawkit.com/product/ai-futurism-illustrations

**Comment by BeccaMelhuish** [comment]
Have looked through both websites and think my preference would be this one from Kevin's original selection - nice style and fairly relevant/easy to adapt activities: 

https://www.getillustrations.com/illustration-pack/gusto-vector-illustrations

Though one thing to consider with whichever pack we end up with, would be making sure they look globally representative in terms of diversity :)

**Comment by kevincrepin** [comment]
Hey,

Had a first couple go's with illustrations for the homepage.

v1: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=1127%3A4370&viewport=-4037%2C133%2C0.25&scaling=min-zoom

v2: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=1309%3A6519&viewport=-4037%2C133%2C0.25&scaling=min-zoom

Since the content for the homepage isn't finalised yet, I only added here and there the illustrations. In other places we will probably show screenshots or simplified UI versions of the platform. Or icons/illustrations that are simpler than the actual illustrations.

But I think this already gives a better idea of what it could look like with adjusted colours.

I also tried with the surrealism, but these files are very complex actually and I'm not sure if we will be able to properly adjust them...

My preference goes to v1 because their simplicity suits the Citizen OS approach and they still have enough personality to be fun. On top of that they are definitely the easiest ones to adapt to our needs.

I will also still deal with social media approaches, but wanted to share this already.

@anettlinno @oksks @BeccaMelhuish 

PS: Also implemented the latest feedback.

**Comment by oksks** [comment]
Thanks @kevincrepin! 
I personally feel like V1 suits us pretty well - it's simple, friendly and doesn't look boring. Having more diversity in the characters is the only request I have - repeating what @BeccaMelhuish has asked for above. We should have a proper representation of the global population. 

Let's see what girls think of these options. I'm hoping to finalize this within the next week.

**Comment by anettlinno** [comment]
Thanks a lot, @kevincrepin!

I also vote for v1 and agree with what @oksks said :)

**Comment by BeccaMelhuish** [comment]
V1 is also fine by me! 

Except for the diversity issue as above, and also not loving these colour combinations below.. But otherwise it's looking beautiful :) 

![image](https://user-images.githubusercontent.com/61320526/173391774-e535ab3d-a369-429c-ae70-763804f0631f.png)

**Comment by kevincrepin** [comment]
I made some changes to have better representation and this also changed the colouring of this illustration.
https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=1127%3A4370&viewport=-1886%2C519%2C0.13&scaling=min-zoom

But yes, I do believe the illustrations should incorporate the logo colours, whereas the UI should be softer. The illustrations are there to help set the branding, but the UI should mainly just be out of the way.

---- 

I also added some social media templates (based on those that Becca shared) so you can get an idea of how it can all start coming together. I recommend also having a recurring pattern for where the logo is located and it also gives the opportunity to add the url for communication. Obviously colours can change, I just made some examples with the new style.

![Screenshot 2022-06-15 at 17 49 06](https://user-images.githubusercontent.com/26792281/173857195-648f3d44-41e9-450f-82ba-65020970c4c2.png)

**Comment by BeccaMelhuish** [comment]
Thank you @kevincrepin, so great to see it all coming together!! 😍

And the illustrations are definitely looking much better diversity-wise, but unfortunately their matching white tops made me think straight away of some kind of religious cult and then also of hospitals..

**Comment by oksks** [comment]
@argoroots, could you please help us with creating the new frontpage, based on Kevin's [design](https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=1127%3A4370&viewport=-1886%2C519%2C0.13&scaling=min-zoom). 
Here's the final copy to populate designs with: [link](https://docs.google.com/document/d/11PIkOFd1GCy9YupCM11lO4Qw57CEziqKhJg2S3I4rjQ/edit?usp=sharing).

Please start with creating a home for templates (like in the [LHV example](https://www.lhv.ee/et/disain/) you've shared), where each "chunk" is to become a standard template, so that we could always reuse the chunks to create pages as needed. :) Each chunk we create from now on is to be added to this catalogue.

Please let us know if there are any questions or issues, and estimate the deadline I could communicate. Thanks!

**Comment by kevincrepin** [comment]
@oksks it makes sense before @argoroots starts with this that I go through the final copy as well and see whether everything still makes sense + there are visual assets for everything.

I requested access

**Comment by kevincrepin** [comment]
@anettlinno @oksks @BeccaMelhuish I added more illustrations to the homepage: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=1127%3A4370&viewport=-4728%2C237%2C0.25&scaling=min-zoom

You can also click on the main features to see the different illustrations for those.

**Comment by BeccaMelhuish** [comment]
It really is shaping up beauuttifully, so good to see 😍🙌

A few minor thoughts to share from me: 

- Not sure if this matters (depends where Argo takes the copy from) but this sentence isn't the right one on Figma:
![image](https://user-images.githubusercontent.com/61320526/176157865-db6f38ee-9c6a-458a-a138-0d2e856e3163.png)

- For some reason this guy makes me think of "[tin foil hat](https://www.google.com/search?q=tin+foil+hat&rlz=1C1NDCM_enEE819EE819&sxsrf=ALiCzsYPNW9_-yc5jroiQnxbSclbbmXuKw:1656412241865&source=lnms&tbm=isch&sa=X&ved=2ahUKEwidpJy6-M_4AhVpS0EAHQg-CDMQ_AUoAXoECAIQAw&biw=2133&bih=1041&dpr=0.9#imgrc=Kq6IYC5ppfcoUM)" people, and not so sure about the halo-like dots..
![image](https://user-images.githubusercontent.com/61320526/176158158-44f3b3d9-9d61-49f1-ab73-0dea97961742.png)

- Something about the colours on this one aren't so beautiful as the others to me: 
![image](https://user-images.githubusercontent.com/61320526/176158393-cde66392-a997-4997-a04d-b559417c2148.png)

- Maybe there could be a big yes tick, or both a yes and no tick but with the yes one shown as "selected" (or something like that), to show more quickly that it's a vote:
![image](https://user-images.githubusercontent.com/61320526/176158586-79390359-f7e1-4c9a-89e2-d8583db692df.png)

But overall really liking how it's looking!

**Comment by BeccaMelhuish** [comment]
And @anettlinno @oksks I guess we need to re think this line (seeing as it might not be for always): 

![image](https://user-images.githubusercontent.com/61320526/176159357-d00d96fd-3b55-48d5-8b6d-a48cf6f32ee1.png)

Maybe: "It's free for everyone! Just log in and get discussing." ?

**Comment by anettlinno** [comment]
@kevincrepin I absolutely love it! So beautiful! @BeccaMelhuish, I think that texts can be changed by Oks as well once it´s developed by Argo :) 

And "Features" design is similar to UX/UI redesign! (Y)

**Comment by anettlinno** [comment]
Later, when we have the templates, we could add there platform illustrations as currently there are no pictures of that. BUT again, we could use those more on the Product page to show people that it is ready-made platform :)

**Comment by kevincrepin** [comment]
Just wanted to let you know I've made a couple updates to the illustrations and. as far as I'm concerned, the designs are ready to start development. We'll probably need some more illustrations for different subpages, but let's tackle those when the content for those pages exists.

**Comment by oksks** [comment]
Thank for your input, guys, it's shaping up really nicely and looks like a web we can be proud of!
@anettlinno is right, exact wording doesn't matter as much, as long as there's approximately the same amount of it - I can update texts anytime.
@BeccaMelhuish - I like your copy version for the bottom chunk, will use it.

---

**OK, moving this into development phase <3** 

@argoroots, could you please help us with creating the new frontpage, based on Kevin's [design](https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=1127%3A4370&viewport=-1886%2C519%2C0.13&scaling=min-zoom). 
Here's the final copy to populate designs with: [link](https://docs.google.com/document/d/11PIkOFd1GCy9YupCM11lO4Qw57CEziqKhJg2S3I4rjQ/edit?usp=sharing).

Please start with creating a home for templates (like in the [LHV example](https://www.lhv.ee/et/disain/) you've shared), where each "chunk" is to become a standard template, so that we could always reuse the chunks to create pages as needed. :) Each chunk we create from now on is to be added to this catalogue.

Please let us know if there are any questions or issues, and estimate the deadline I could communicate. Thanks!

**Comment by oksks** [comment]
@argoroots could you please provide an estimate for completion of this task? It's been 2 weeks. 
Thanks!

**Comment by oksks** [comment]
@argoroots ?

**Comment by argoroots** [comment]
@oksks I think, that it is possible to finish it this week.

**Comment by oksks** [comment]
@argoroots how we doin'? :)

**Comment by argoroots** [comment]
There are all front page sections now done and visible https://citizenos.com/v2/design.

**Comment by oksks** [comment]
@argoroots 
Could you please adjust the following items on frontpage's V2:

- [ ] COS videos should play within the page - same solution as right now on the website
- [ ] "Who uses our platform" section - clicking "Read more" CTA's should expand the text in the same view
- [ ] Hide "Quick-start with our templates" section for now (but please leave it there in the code), as we don't have templates yet
- [ ] "What motivates us" chunk - in the code there seems to only be a placeholder for the image, could you please add a location for the user's name, their company and quote, into the code. Please create one generic sample of a user quote on the page for visual review of it.

Please kindly provide an ETA for this task. Thank you!

**Comment by argoroots** [comment]
@oksks, please test.

**Comment by oksks** [comment]
All good, done and live, thanks @argoroots!! :)
