### ISSUE TITLE
TASK: Get search keywords from the Help Centre 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#306]
**What needs to be done?**
We would like to able to analyse what our users input into the search bar as part of our Know Our Users project. 

![Screenshot 2022-06-15 at 13 18 02](https://user-images.githubusercontent.com/72747107/173804535-af4bcd8b-4bd4-47dc-ba9d-85e0751198df.png)

For our Know Our Users project, we need to collect aggregated and anonymised data about user activities such as search keywords. This helps us to better meet our users needs and improve their experience with the product.

**Location**
https://citizenos.com/help

**Any additional files or info needed?**
Maybe this is a helpful example of what we need –  #https://citizenos.com/help/search?q=hello+world

**Deadline**
June 25th because the report will be presented by the end of June

**Comment by oksks** [comment]
Wow, that's superfast! Thank you @argoroots <3 
@ssin1901 could you pls check and let us know if you've got what you needed? :) Thanks!

**Comment by ssin1901** [comment]
@argoroots thanks a million ! Got what is needed.

**Comment by ssin1901** [comment]
@oksks thank you too!
