### ISSUE TITLE
Disappearing Yes/No field in the Help Center

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-web#307]
**Disappearing Yes/No field**  
After responding to the "Was this helpful? Yes/No" field, that section vanishes! My thoughts are that the flow should be that after submitting either Yes or No, there is confirmation that the responses was submitted, and then the box remains in the same place but with the Yes or No (whichever they chose) in a different shade. (We may also want to think through how it works if they want to change their mind and switch it to the other option - yes or no).
 @anettlinno shall we ask Kevin to design this flow and then ask Argo to develop it?  

_Originally posted by @BeccaMelhuish in https://github.com/citizenos/citizenos-fe/issues/815#issuecomment-1134454374_

**Comment by kevincrepin** [comment]
We actually had this notification but somehow I didn't take it into the prototype :s
https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?node-id=3334%3A41759

**Comment by oksks** [comment]
@argoroots, could you please implement Kevin's design. Thanks!

**Comment by oksks** [comment]
Seems to be done - tested and it works. Closing.
