### ISSUE TITLE
Search bar problems

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-web#308]
**Search bar problems**
The problem (which Liina previously discussed with Argo) was that the way the search bar works is that if the word appears in the heading or the text then it shows up in the search results. But if the word is not typed exactly the same way as it is in the text, it doesn't appear. So for example, "invitation" brings up zero results, as I only use the shortened word "invites" in the texts. I assume one way to fix this would be the have hidden keywords (in the code but not visible to the user) that we add ourselves, so that they would be pulled up in search results. But just a guess, would need Argo to confirm how this could work.  

![image](https://user-images.githubusercontent.com/61320526/169791826-84089ff9-0953-4b71-9aba-e6d79304b701.png)

The other problem is that for me (and I assume for others too - could someone confirm?) when I click in the search bar, it flashes up with suggestions from previous searches, but they are not all relevant to this site - they are searches I have made in other places (on Google for example, re the baby gifts):

![image](https://user-images.githubusercontent.com/61320526/169792516-67f64666-b90f-4ee6-9145-d0bf3a1c92e5.png)

And when I start typing, it does the same, for example when I type "P":

![image](https://user-images.githubusercontent.com/61320526/169791941-32a01420-f9aa-48a1-acc4-a4e3e5f8b6a1.png)

Earlier in the thread, after discussing these search issues with Argo, Liina said: 
_"I've agreed with Argo, that he will not do any work from now on unless you ask him to, @anettlinno (to keep spending in control). This is up to you Anett, to decide when and if to fix this search issue."_
So @anettlinno what do you think, do we go ahead and ask Argo to fix these? Search is a very important element to get right I think.. 

Tagging @oksks too, just for info as it's website related :)

_Originally posted by @BeccaMelhuish in https://github.com/citizenos/citizenos-fe/issues/815#issuecomment-1134454374_

**Comment by anettlinno** [comment]
@oksks do we know how much work it is for Argo to fix the search bar issue? Additionally, @ssin1901 do we have data about how often our Users currently use the search bar in Help Center. If we know these two things then we can make the decision :)

**Comment by ssin1901** [comment]
@anettlinno we have four unique conversions for the search bar (i.e 4 different visits) and 23 conversions in total.

**Comment by oksks** [comment]
@BeccaMelhuish - I confirm, for me search bar acts the same way (Chrome) - it pulls up my Google search history in both cases, which is bad UX and should definitely be fixed asap.

@argoroots could you please comment on the questions, propose solutions and estimate fix time? Thanks!

**Comment by BeccaMelhuish** [comment]
@argoroots An additional issue which I just discovered. When searching for "co-creating a topic text" when I type in just "co-creating" it finds nothing: 

https://github.com/citizenos/citizenos-web/issues/309

Whereas typing in "topic text" does find the topic in question: 

![image](https://user-images.githubusercontent.com/61320526/181012785-c22996b8-91c8-4642-96df-1d69fd8b5ecc.png)

**Comment by BeccaMelhuish** [comment]
It would also seem to be better UX if there was a message saying "No results found" in such situations, as currently it just comes up blank.

**Comment by argoroots** [comment]
@anettlinno I can add special search keywords field to search pages where You can store words what must find this page. Should I?

I removed search field autocomplete and improved search to find certain words what @BeccaMelhuish mentioned.

**Comment by argoroots** [comment]
@oksks, There is one service for site search: https://www.algolia.com/products/search-and-discovery/hosted-search-api/

Should I implement it?

**Comment by oksks** [comment]
@argoroots thanks, just checked, seems legit - is it free to implement? I'd love to test it out and see how it works with the languages I speak.

**Comment by argoroots** [comment]
@oksks, up to 10000 search per month is free: https://www.algolia.com/pricing/

**Comment by oksks** [comment]
Works for us then, let's do it - thanks @argoroots !

**Comment by oksks** [comment]
@argoroots Hi, is this implemented and can be tested and closed?

**Comment by oksks** [comment]
Tested, seems to be working, closing.
