### ISSUE TITLE
TASK: Help Center layout/navigation issues

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#309]
**Background info**
We've gone through the Help Center and found a some behaviour/layout issues we'd like to iron out, for HC to function as intended and be convenient for users. Ticket with detailed info can be found [here](https://github.com/citizenos/citizenos-web/issues/302).

**Issues to resolve**
---- 
- [x] **1 - Fix back button behaviour.** [link to original comment](https://github.com/citizenos/citizenos-web/issues/302#issuecomment-1156529559)
Set up postMessage system so that @ilmartyrk can send command from APP to website inside iframe to go to previous page, instead of home. https://html.spec.whatwg.org/multipage/web-messaging.html#security-postmsg.
According to @ilmartyrk, this means that @argoroots should add a few lines of code to the webpage:
```
window.addEventListener('message', function (e){
	if (/citizenos\.com(:[0-9]{2,4})?$/.test(e.origin) && e.data === 'back') {
      window.history.back();
    }
}, false);
```
---- 
- [x] **2 - Margins**
The current live version has some margin issues. In some cases too much, in others too little, couple examples:

- The margins all around the content feels a bit too tight, like it's all crammed into this small space.
- start page after the first paragraph there's a big margin until the search and then another big margin until the topics. In design this is not so big.
- The related or quick links need a bit more margin between the list items + the text should act like in a list, so if a wide sentence falls on a second line, it should be aligned with the first word of the sentence, behind the arrow.

![](https://user-images.githubusercontent.com/26792281/173854705-a0de526e-4a9c-4204-ab20-0131999ae923.png)
---- 

- [ ] **3 - White box overlay**
In the bottom there's a white box blocking the content for @kevincrepin, looks a bit weird :) 

![](https://user-images.githubusercontent.com/26792281/173855242-bf51fe97-ce66-408d-97e5-e29136b6c2aa.png)
---- 

- [ ] **4 - Reactive top title/label**
The idea was that the top title/label would change according to the second (not third) level. This would also reduce the need for the breadcrumbs.

![](https://user-images.githubusercontent.com/26792281/173855520-f5f5d612-3f2a-4332-b9c0-4fe869eb3a48.png)
---- 

- [ ] **5 - Letter spacing**
Minor: The top title/label should have a bit extended letter spacing, like in design. It looks better :)

---- 
- [ ] **6 - Level alignment**
Margin issues on the website: as Level 1 is aligned, but Level 2 indented. It looks quite odd when jumping back and forth between them, and isn't how it was in Kevin's original design.
---- 

**Location**
https://citizenos.com/help/

**Deadline**
@argoroots, could you please estimate the deadline?

**Comment by BeccaMelhuish** [comment]
Thank you @oksks! 

As all of these except #6 relate to the way the content is displaying on the platform version, am wondering if it will need work from both sides - @argoroots on the website and @ilmartyrk on the platform - to get it displaying just right on both? 

Will also add the links to the designs again here too, for ease of comparison between what it is currently looking like and how Kevin initially designed it :) 

**Web version design:** https://www.figma.com/file/eHBSunqUv10fMcWmiEEXiv/Website?node-id=117%3A1463
**Platform version design:** https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=586%3A21598

**Comment by BeccaMelhuish** [comment]
@ilmartyrk did you have some thoughts on which of these things above would need to be done by Argo, and which by yourself, or a combination of the two of you? As it would be really good to get them fixed soon I feel - especially the back button behaviour as a priority, as that's really dodgy UX at the moment, but the rest would be good to have tidied up too to have it looking slick :)

**Comment by BeccaMelhuish** [comment]
And just to clarify for number 4, copied below, the idea is to remove the breadcrumbs from the platform version once the top titles are (hopefully) fixed, right? As Kevin confirmed that this was unnecessary there, and makes unnecessary clutter. (Whereas on the website it is very useful - it is making navigation so much easier already!).  

_4 - Reactive top title/label
The idea was that the top title/label would change according to the second (not third) level. This would also reduce the need for the breadcrumbs._

**Comment by argoroots** [comment]
1 and 2 are fixed.
3–6 are in app side and is for @ilmartyrk.

**Comment by BeccaMelhuish** [comment]
Hey @oksks and @argoroots - just had a look and No. 1 (back button) doesn't seem to be fixed to me.. Is there something that @ilmartyrk needs to do to make whatever changes Argo made come into effect? 

And just to recap on the problem, when you are in a "Level 2" page on the platform, like in the screenshot below, it takes you back to "Home", but it should take you back to where you just were. (I.e. to "Topics" in this case). 
![image](https://user-images.githubusercontent.com/61320526/195668545-8b602a83-4734-4689-890d-3d311a1c02fa.png)

**Comment by oksks** [comment]
@argoroots, please review @BeccaMelhuish's comment above.

**Comment by ilmartyrk** [comment]
@oksks @BeccaMelhuish back button is working now as it should

**Comment by BeccaMelhuish** [comment]
Awesome, thank you @ilmartyrk! Though a bit of an odd thing seems to happen when you go back to the page you were just on. Instead of taking you back to the top of the page you were on (like would usually happen when you click "back" in a browser) it takes you to where you were on the page before when you clicked to enter the next level. 

This is quite weird UX and quite disorientating/confusing as you don't see the heading at the top to orient yourself, if you were further down the page when you clicked through.. 

Is it possible to make it go back to the top of the previous page instead? 

Also please let me know if you think you are able to fix the headings and hyperlinks and remove the breadcrumbs (from the platform only), or if we need to ask Argo to help with these things :) 

![image](https://user-images.githubusercontent.com/61320526/209337582-443f499a-3808-4b50-a0b1-dd6f28f52f25.png)

Or maybe @oksks you're able to see in the code what has gone wrong with the headings and hyperlinks, as I see they are displaying wrong in the website too now (but it's only recently this has happened - before they looked great..)?   

![image](https://user-images.githubusercontent.com/61320526/209337795-b2fdb76b-eeca-43d1-909f-d41e3ee3480a.png)

**Comment by argoroots** [comment]
links and nav fixed

**Comment by argoroots** [comment]
Please make smaller tasks. Following this megatask is more difficult than making requested code fixes/changes.

**Comment by oksks** [comment]
Thanks, @argoroots, and feedback noted - will break tasks into smaller increments, and eject new tasks out of super long threads. Sorry for this.

**Comment by BeccaMelhuish** [comment]
@oksks Headings are all still very big, or is this under a different task? :) 

![image](https://user-images.githubusercontent.com/61320526/227212281-aabba554-91f0-46f9-8f86-91542c5a75df.png)

**Comment by BeccaMelhuish** [comment]
And @ilmartyrk are you able to remove the breadcrumbs from the platform version, or how can this be arranged? As per Kevin's previous input they are only needed on the website version of the HC, and are adding unnecessary clutter on the platform version.. 

![image](https://user-images.githubusercontent.com/61320526/227212746-6f2431c0-51af-410d-89ed-ecb96b957429.png)
