### ISSUE TITLE
PAGE: Democracy Defenders Accelerator

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#318]
**What needs to be done and why?**
1 main page with 2 sub-pages for the DDA project. 

**Location**
URL should be www.citizenos.com/DDA
Should sit under "projects" in the website structure. 
@ssin1901 shall we replace PYLN with this for now (as PYLN no longer exists? Or I'm mistaken?), on [this](url) page? But put it at the top? 

**Future path/style block name**
@oksks Sorry I didn't understand this one - let me know if there's something else you need here :) 

**Main banner image**
Banner (same for all 3 pages, main and subs) is [here](https://drive.google.com/drive/folders/1nZY-2zMjgaiyl4Nr-KBusCmDv_5zW7bz?usp=sharing) - one darkened, one clear, depending what you need.

**Page content**
- Texts and graphics are [here](https://drive.google.com/drive/folders/1FXMKijffb_Tiqks6nznuSv65g_vZi2Gl?usp=sharing). 
- As discussed on Slack all the sections highlighted bright green are ready to go. 
- Paler green ones you could add the text already, they are only currently missing links at the moment which could be added later. 
- (Though I'm confused about why some of the sections I had previously made green were no longer green - had one of you changed them @oksks @ssin1901? Or maybe I am misremembering, also possible!) 
- I highlighted in blue and tagged @oksks in things that changed since I first shared the doc with @oksks, just to try and avoid confusion. @oksks - maybe you can reply "done" like you do in the HC doc once these changes have been made (or "noted" if you hadn't uploaded that text yet anyway)? Then I can remove the blue highlights. 
- As per the comment in the doc, the ******** shows where we would like a new background section to start, alternating between white and grey. Or adding in some other colours as the background to particularly important sections if this is possible @oksks? If so, please let me know and I can mark which are the more important sections to bring out with colour :) And just to be clear, this is what we mean by background sections:
![image](https://user-images.githubusercontent.com/61320526/192334891-14ff6edf-8a6b-4674-86e5-0c8633031d79.png)

**Page description for search results**
The Democracy Defenders Accelerator is a 10-month civic engagement programme, bringing together young activists from diverse backgrounds to learn, exchange and grow together.

**Page keywords**
Civic Engagement 
Participatory Leadership 
Civil Society 
Activism skills
Democracy training
Open society
Activism mentoring
Civil society training programme
Activist training
@oksks are these the right sort of thing? @ssin1901 any others to add? 

**Is the page translatable?**
Yes it needs to be in Estonian as well as English - discussion started on Slack about this with @anettlinno and @ssin1901. 

**Deadline**
Needs to be live by the end of the week very latest, but ideally sooner! But @oksks what are your working days this week and when do you think you might be able to show us a first version of how it's looking, so we can give feedback if anything needs adjusting before the end of the week?

**Comment by BeccaMelhuish** [comment]
Just adding here that it's confirmed by @ssin1901 that we can replace PYLN on the projects page with DDA :)

**Comment by oksks** [comment]
>Should sit under "projects" in the website structure.

@BeccaMelhuish - the URL would then be citizenos.com/projects/dda, was that what you've had in mind? And also then we should move https://citizenos.com/civic-hackathon/ to https://citizenos.com/projects/civic-hackathon/, too?
Or you've meant I should link to DDA page from under the "projects" tab, just like with the CH page?

**Comment by BeccaMelhuish** [comment]
@oksks Ah OK no I think it would be best to keep the URL as just /DDA. So yes, more the latter - just link to it from the projects page :)

**Comment by oksks** [comment]
@BeccaMelhuish I haven't changed any coloring. :)

Future path/style block name - basically, template name for this kind of block, should it be generalized. In case with this page,  it's likely "Event page template" so it's easy to find in the future.

Will mark uploaded blue commented parts with "Done".

>Or adding in some other colours as the background to particularly important sections if this is possible @oksks?
Not possible now, can request for the future.

Keywords - great stuff, thanks. Maybe something less generic, too? Like "democracy training" or something similar - what would actual, real people search for, if they wanted to find a page like our DDA page?

I'm working tonight + tomorrow lunchtime and late evening, and a full day this Thursday or Friday, have to confirm exact day yet - no worries, the English version be live by the end of the week. :)

**Comment by BeccaMelhuish** [comment]
Wonderful all good, thank you @oksks!

Have added a few more ideas to the key words list now :)

**Comment by ssin1901** [comment]
Hey @oksks , here are the form links


1. DDA Application form: https://forms.gle/ZonycpdDouu9yTTQ8

2. DDA Information Seminar - November 1
https://forms.gle/2EP189WGSqvXpmyJ9

Tagging @BeccaMelhuish

**Comment by oksks** [comment]
DDA is live :) Are you good with closing this issue @BeccaMelhuish ?

**Comment by BeccaMelhuish** [comment]
Hey @oksks yes looks good to me thank you!

Only very minor thing, could you remove this date please (on DDA homepage), just for consistency:
![image](https://user-images.githubusercontent.com/61320526/195667243-6261a8fe-27f2-4e73-a0fe-1c35abece18e.png)

And is the page jumping function (links at the top that take you further down the same page) cutting off the top of the subsection title that could be fixed by Argo in the nearer term, or it will have to wait? Would be great if possible.. 

But otherwise yes all good with closing it :)

**Comment by oksks** [comment]
Hi @BeccaMelhuish - I've fixed the dates, however I have to ask @argoroots to help with the preview fixes.
Argo - could you please sort this out as soon as possible? Thanks!

**Comment by argoroots** [comment]
Page title (_title_ field in data.*.yaml files) should not include HTML.

**Comment by BeccaMelhuish** [comment]
@oksks Two more requests for a text update please! Have tagged you in comments in the relevant places :) 

[Homepage](https://docs.google.com/document/d/1fA2YwvAFZNaBlieVBTjoc8ta2c8LK-I8kzNFmHGxQDI/edit?usp=sharing): 
![image](https://user-images.githubusercontent.com/61320526/196610826-7b5f09f7-6984-4eed-ac0a-afd2cf0513db.png)

[Programme page](https://docs.google.com/document/d/1ImfG0IO4piIsyaO9bwNRTM102b7aYCxqlTAYI8IBV9o/edit?usp=sharing):
![image](https://user-images.githubusercontent.com/61320526/196611890-2a4f9647-b17d-437f-9efe-a8b6f2d97ab1.png)

**Comment by BeccaMelhuish** [comment]
Hey @oksks! As per Sara's comment in Slack, some issues here:

![image](https://user-images.githubusercontent.com/61320526/197042697-3a6a3467-c261-4847-a2a7-a18fed837fcf.png)

The same <br> thing as in the social media preview - is this from the vertical line perhaps? If possible to fix it would be great, it's cropping up in a few places.

And suggested replacement copy: 
_An immersive 10-month civic leadership programme for young activists, delivered by Citizen OS._ 

Also, we now have a slightly adjusted [applicants infopack](https://drive.google.com/file/d/1eyMKvNIKqDVcuW51z5p5HgpUtaj89dcn/view?usp=sharing), would you be able to switch it over please? (In a way that doesn't affect the URL for it, if that's ever a risk).

**Comment by oksks** [comment]
@BeccaMelhuish Hi, I've updated the text on homepage and programme pages.
The <br> issue was already fixed by @argoroots, I believe - as per his comment above.

Did you mean I should replace the title of all 3 pages with the replacement copy you've provided? Or what's that for :)

**Comment by BeccaMelhuish** [comment]
Hey @oksks, thank you! 

If you Google "Democracy Defenders Accelerator" currently you get this, still with the "br" showing, and the replacement copy was for the text marked red here: 

![image](https://user-images.githubusercontent.com/61320526/197217112-e79eb5d0-a131-41ad-8610-2aea432456dd.png)
  
Also, we now have a slightly adjusted [applicants infopack](https://drive.google.com/file/d/1osvXQ5c5fWFm9-ElJ8yAjKjVGjP28hVm/view?usp=sharing), would you be able to switch it over please? (In a way that doesn't affect the URL for it, if that's ever a risk!). 

And we would like to try changing the title of the "Application guidelines" page to "Application process" to see if it brings more traffic (not many people visiting this page at the moment). Will this cause any complications to change, or it's straightforward?

**Comment by oksks** [comment]
@BeccaMelhuish ah gotcha. Will replace the text in 5mins. 
Will also replace the infopack file, it won't affect the URL.
Application guidelines > process is an easy change as well.

**Comment by BeccaMelhuish** [comment]
Super thank you @oksks!

And for the application guidelines, please change it here (homepage) too, as well as at the top :) 
![image](https://user-images.githubusercontent.com/61320526/197218560-d183aedf-6ae6-4c92-85f1-71f5b39b77a9.png)

**Comment by oksks** [comment]
Done @BeccaMelhuish - changes to be live in a couple of minutes. 

>If you Google "Democracy Defenders Accelerator" currently you get this, still with the "br" showing

If I'm not mistaken, Google takes a while to crawl the pages and refresh the preview content? It doesn't sync immediately.

**Comment by BeccaMelhuish** [comment]
@oksks OK thanks very much! Will keep an eye on it then :) 

And just added 3 minor text tweaks for you in comments on the [Programme page](https://docs.google.com/document/d/1ImfG0IO4piIsyaO9bwNRTM102b7aYCxqlTAYI8IBV9o/edit?usp=sharing) too, not urgent though!

**Comment by BeccaMelhuish** [comment]
Hey @oksks! Seems like the updates here didn't work, as it's been a few days now? 

![image](https://user-images.githubusercontent.com/61320526/197485266-ba180323-740d-4eb2-9c9e-caa5935ee817.png)

**Comment by ssin1901** [comment]
Hey @oksks @BeccaMelhuish seems to be resolved now 
![Screenshot 2022-10-26 at 15 38 29](https://user-images.githubusercontent.com/72747107/198029022-8fcab3b0-185b-4e57-9679-96c9fa16f0af.png)

**Comment by BeccaMelhuish** [comment]
Great! Though still the old sentence showing up here.. 

![image](https://user-images.githubusercontent.com/61320526/198057015-9f93f69c-5916-43cf-a09b-5653e0b24a19.png)

**Comment by ssin1901** [comment]
@BeccaMelhuish thank you for noticing! @oksks yes the <br> us resolved but as Becca mentioned it still says 10 days instead of 10 months.

**Comment by BeccaMelhuish** [comment]
@ssin1901 @oksks One odd thing, in social media preview this sentence comes out correctly now, but still not in Google search results.. 

![image](https://user-images.githubusercontent.com/61320526/198141436-1bb86fe6-dc2c-461d-86aa-173fb903828b.png)

**Comment by BeccaMelhuish** [comment]
Hey @oksks I just checked the above again and its still saying its a 10-day programme in Google search results.. Anything that can be done to fix that? Also is showing th e "br" things again for some reason! (Which I thought was fixed already, but maybe am misremembering)

![image](https://user-images.githubusercontent.com/61320526/201345878-2303eea1-0b43-46a9-9848-c52079eb6d74.png)

**Comment by BeccaMelhuish** [comment]
@oksks As per the Slack thread, we've got a few changes to request now that applications have been closed :) 

Here is a mockup of how the "Apply" box should look now, and I've added in blue where other edits should be made, in the Google docs: 

- [DDA Homepage](https://docs.google.com/document/d/1fA2YwvAFZNaBlieVBTjoc8ta2c8LK-I8kzNFmHGxQDI/edit?usp=sharing)
- [DDA Application Process](https://docs.google.com/document/d/1HvTPFQSyJG4R5K7yfmFyoQ0lECmdLpkXIuVVKrW8RuU/edit?usp=sharing)

(All confirmed by @ssin1901).

Will send you the Youtube link as soon as I have it (so I guess leave the info seminar related edits until I send it).   

And just a reminder about the timezones on the [Programme](https://docs.google.com/document/d/1ImfG0IO4piIsyaO9bwNRTM102b7aYCxqlTAYI8IBV9o/edit?usp=sharing) page - also in blue and comments :) 

Thanks a million!

**Comment by oksks** [comment]
Hey hey, not sure what I can do about the "10-day" and <br> issue, as everything is correct on our side, I've just double-checked.

About deactivating the button - I've just spent 1.5 hours, trying to do that and then googling what can be done - the button is hardcoded into the template and I can't remove it. Wrote to Argo, asking to assist me with this ASAP. 
Sorry, I had no way of knowing of this sooner than trying to remove it and push changes to live :(

**Comment by BeccaMelhuish** [comment]
@oksks ah that's a shame about the Google search results - maybe Argo could advise, in case there's a trick to it? 

And no worries re the button! Maybe we just make the button say "Applications closed" for now at least. 

And @ssin1901 you will close the form now, right? Then even if they do click on it, they won't fill out the form..

**Comment by BeccaMelhuish** [comment]
@oksks just FYI @ssin1901 has closed the form now :)

**Comment by BeccaMelhuish** [comment]
On reflection I think it might look pretty odd to have a button that says "Applications closed" as I suggested above? So we could also just stick to the original plan (the mockup screenshot above), and nevermind if people click the Apply button, they'll find out soon enough that it's closed.. Or maybe there's another solution? Link to the Applicants infopack from the button instead perhaps?

**Comment by oksks** [comment]
@ssin1901 @BeccaMelhuish 
Argo has removed the button and fixed the template tonight, so that it would be possible for me to hide it (for future events' sake).
I've tried to implement the screenshot from above, but seems like the template prohibits any text wraps AND formatting :D So I did a workaround and added text as a headline:
 
<img width="355" alt="Screenshot 2022-11-13 at 23 26 24" src="https://user-images.githubusercontent.com/34126353/201545391-b7b888ff-f4e8-4d4b-a248-12f373855038.png">
Pls let me know if that works OK or if further changes are needed. Changing text is easy.

The text/date changes in all 3 pages of DDA are also done now.

**Comment by BeccaMelhuish** [comment]
Thank you @oksks! 

Works for me :)  

I think let's change the box heading to this though now (a bit repetitive with the other headings but at least not mixed messages): 

![image](https://user-images.githubusercontent.com/61320526/201613927-335bbdb4-a91c-4b4e-b4ab-280cb2d021a6.png)

**Comment by BeccaMelhuish** [comment]
@oksks Info seminar Youtube video link is now ready! Will also add to the relevant places in the docs :) 

https://www.youtube.com/watch?v=1Vi3Is3AB78

**Comment by oksks** [comment]
@BeccaMelhuish could you please review the question above?

**Comment by oksks** [comment]
Sidebar updated as requested

**Comment by BeccaMelhuish** [comment]
Sorry @oksks totally missed this, but yes that's fine thank you :)
