### ISSUE TITLE
TASK: Replace project/block from citizenos.com/projects

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#335]
**What needs to be done?**
Replace Civic Hackathon image and text 

![Screenshot 2022-10-18 at 11 48 31](https://user-images.githubusercontent.com/72747107/196383247-ac4e6569-c5ad-4225-a080-3f6c72bbb18e.png)

With new image and text 

Image (left): @BeccaMelhuish 

**Structure (right)**
**Heading**: Democracy Defenders Accelerator
**Body**: An online and offline 10-month programme where participants learn to design and deliver civic engagement projects, as well as practice participatory leadership.  
**Button**: “Learn More” -> https://citizenos.com/dda

**Location**
Citizenos.com/projects

**Any additional files or info needed?**
@BeccaMelhuish image on the left?

**Deadline**
27 October

**Comment by BeccaMelhuish** [comment]
@oksks wondering if you saw this one, so tagging you again just in case not :) (Not that it's urgent though)

**Comment by oksks** [comment]
Done! Sorry for the delay. 
Please check and confirm that's what you've wanted - the image looks a bit bleek, wdyt, maybe let's do a more contrast-ey version? 
Unfortunately, can't swap the last block's photo with the text so it would make sense in the alignment, it's built this way. :/

**Comment by oksks** [comment]
@BeccaMelhuish I've just checked - there's standard space between chunks in the code, so there's nothing I could remove, unfortunately. 
Awesome re: the Youth Exchange project - please create a new ticket when the content's ready :) Thanks!
