### ISSUE TITLE
BUG: DDA Applicant Information Package loads blank PDF  

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#338]
**Describe the bug**
The pdf on the following page is blank. 

https://citizenos.com/assets/files/DDA_Applicants_infopack.pdf (also see screenshot)

It needs to be **replaced** with a new pdf (sent to @oksks)

**How critical is the bug?**
Urgent/Critical. 

**To Reproduce**
1. Go to https://citizenos.com
2. Scroll down to end of the page3. 
3. Click on https://citizenos.com/assets/files/DDA_Applicants_infopack.pdf

**Expected behavior**
PDF should loads all 15 pages 

**Screenshots**

![Democracy Defenders Acceleratorbr 20 Jan - 17 Nov 2023 · Citizen OS 2](https://user-images.githubusercontent.com/72747107/198878805-4e28130a-0cc6-4f94-bab2-629c204735ea.png)

**Desktop (please complete the following information):**
 iPad and MacOS Chrome and Safari.

**Smartphone (please complete the following information):**
 iPhone 6 Safari 
 
**Additional context**

**Comment by oksks** [comment]
Ouch, probably caused by me - I did download the file after replacing it to check that it downloads, but I didn't realize I should open it, too. Sorry! Fixed. 
https://citizenos.com/assets/files/DDA_Applicants_infopack.pdf
