### ISSUE TITLE
TASK: Add team description to the page Democracy Defenders Accelerator (New Section)

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#339]
**What needs to be done?**

**Content**
SECTION
HEADING 
Project Team, Facilitators and Mentors

SUBHEADING 
Sara Sinha, project manager, facilitator and mentor

IMAGE
@BeccaMelhuish 

BODY COPY
Sara Sinha is the Partnerships and Community Lead at Citizen OS. Sara has
expertise in digital governance and accessibility in design.

LINKS
Icon: @BeccaMelhuish 
URL: @BeccaMelhuish 

SUBHEADING 
Agustina Iskandar Crombach, participant onboarding lead, facilitator and mentor.

IMAGE
@BeccaMelhuish 

BODY COPY 
Agustina is the Partnerships Lead in Indonesia. Agustina has coordinated and led high impact projects and successfully manages a large network of volunteers.

LINKS
Icon: @BeccaMelhuish 
URL: @BeccaMelhuish 

SUBHEADING 
Wawan Putra, facilitator and mentor.

IMAGE
@BeccaMelhuish 

BODY COPY
Wawan is an expert in programme monitoring, evaluation and capacity
building in the areas of sustainability, gender equality and social inclusion.

LINKS
Icon: @BeccaMelhuish 
URL: @BeccaMelhuish 

SUBHEADING 
Fara Olivia Rumere, facilitator and mentor.

IMAGE
@BeccaMelhuish 

BODY COPY
Fara is an expert in Gender and Statistics. As a UN Women National Youth Gender Activist and a founder of the online platform Sa Perempuan Papua, her focus is on supporting women’s wellbeing and entrepreneurial capacity.

LINKS
Icon: @BeccaMelhuish 
URL: @BeccaMelhuish 

SUBHEADING 
Margo Loor, facilitator and mentor.

IMAGE
@BeccaMelhuish 

BODY COPY
Margo Loor is the co-founder and technology evangelist of Citizen OS. Margo is highly skilled in discussion design and coordinating discussion initiatives on an international scale.

LINKS
Icon: @BeccaMelhuish 
URL: @BeccaMelhuish 

SUBHEADING 
Anett Linno, programme coordinator, facilitator and mentor.

IMAGE
@BeccaMelhuish 

BODY COPY
Anett Linno is the CEO of CitizenOS. Anett has over fifteen years of experience in the field of civic initiatives around the world and specialises in the development of education programmes.

LINKS
Icon: @BeccaMelhuish 
URL: @BeccaMelhuish 

**Location**

https://citizenos.com/dda/programme -> bottom of the page 

**Any additional files or info needed?**
For layout reference

![Screenshot 2022-11-08 at 19 03 42](https://user-images.githubusercontent.com/72747107/200629249-e9804541-950f-42b7-a101-39a344e93027.png)

**Deadline**
14/11/2022 (if possible)

**Comment by BeccaMelhuish** [comment]
@oksks @ssin1901 I've now added this text to the [relevant Google doc](https://docs.google.com/document/d/1ImfG0IO4piIsyaO9bwNRTM102b7aYCxqlTAYI8IBV9o/edit?usp=sharing) in the relevant place (where Sara and I discussed that it should go - at the end of the programme sub-page). 

I added the LinkedIn links, like this (so no need for icons).
![image](https://user-images.githubusercontent.com/61320526/204008043-7922663b-8e88-4516-9669-a2ba34590490.png)

And @oksks presumably it's not possible yet to have the photos alongside the texts like in the PDF above, so let's just leave them out and have text only (unless you have an idea for how to make them work/Argo already made a template, in which case I can send photos too). But I think prob not worth the effort at this point :)

**Comment by oksks** [comment]
@ssin1901 @BeccaMelhuish done, please check it at the [programme](https://citizenos.com/dda/programme) page. 
I've also added a link to the section to the top navigation, and placed LinkedIn links on separate row,s as I feel this structured the sections better visually, sort of having a beginning and end - let me know if you prefer it the originally requested way.

Could you please kindly assign any new issues to me in Github?

**Comment by BeccaMelhuish** [comment]
Looks great to me thank you @oksks!!

**Comment by BeccaMelhuish** [comment]
P.S. @oksks just a couple of edits added above, in case you didn't see as I edited them in after commenting :)

**Comment by oksks** [comment]
Done! :)
