### ISSUE TITLE
TASK: Add Youth Exchange block to Projects page

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#343]
**What needs to be done?**

The following block to be added to the Projects page. (Ideally right-aligned between the two left-aligned blocks at the bottom?):

**Erasmus+ Youth Exchange** 

In our ʻDigital Transformation for Civic Engagementʼ youth exchange programme, Europe’s next generation of leaders learn civic engagement project design and participatory leadership, through hands-on ʻlearning by doingʼ methods.

Photo [here](https://drive.google.com/file/d/1kV4he1GlVJH3-vnaRe4XEK7ZARYnc5Ja/view?usp=share_link)  @@

**Location**
www.citizenos.com/projects 

**Deadline**
As you wish :)

**Comment by oksks** [comment]
Anyway, it's done - please review and let me know if this issue is good to be closed :) https://citizenos.com/projects

**Comment by oksks** [comment]
@BeccaMelhuish may I close it please?

**Comment by BeccaMelhuish** [comment]
Oops sorry @oksks I missed these! 

But yes Learn more should be to [here](https://participationpool.eu/project/leading-by-doing-digital-transformation-for-civic-engagement/) please :) 

And then it can be closed, thanks so much!

**Comment by oksks** [comment]
Done! :)
