### ISSUE TITLE
BUG: HC not working/looking as it should

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#357]
@ilmartyrk @oksks On the platform HC, it seems there's quite a lot of things that seem to have changed since I last looked, and are no longer working/looking as they should be, see screenshot and bullets below. 

The first one is a really important one to fix quickly I think, as it's totally broken, the others just look bad..

- The back button doesn't work at all now (nothing happens when I click it)
- The headings have turned to body font
- The hyperlinks no longer look like hyperlinks

![image](https://user-images.githubusercontent.com/61320526/208724486-4bc2d199-67d3-4d60-a4b3-8ba90c158849.png)

**Comment by oksks** [comment]
This is resolved via https://github.com/citizenos/citizenos-web/issues/309
