### ISSUE TITLE
TASK: Remove Rahvaalgatus stats from website platform stats

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#358]
@ilmartyrk @oksks - am copying this over from Slack as discussed :) 

@anettlinno, @ssin1901 and I have discussed the overall COS usage stats we'll be including in the annual report and decided not to include the Rahvaalgatus stats. So we'll need to take them out of the stats we show on the website too - to be consistent and also more honest.

Is this easy to do? Am I right in thinking there is a set number of Rahvaalgatus stats that are automatically added into the platform stats, so we can just remove those?

![image](https://user-images.githubusercontent.com/61320526/211396838-e627089f-8828-4e89-bf8f-c376e8d673b5.png)

**Comment by BeccaMelhuish** [comment]
And copying over @oksks's reply too, so we can continue the conversation here :) 

"@ilmartyrk is this something you can handle, or I should work with Argo on it?"

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @oksks @ssin1901 @anettlinno I believe rahvaalgatus stats are added on the web side to the current stats that come from API https://api.citizenos.com/api/stats so it should be Argos thing to solve

**Comment by BeccaMelhuish** [comment]
OK thank you @ilmartyrk! 

@oksks might you be able to ask Argo to remove them fairly swiftly? I'm hoping we'll have the Annual Report ready to put out within the next week, and would be best if the website is saying the same thing when we do..

**Comment by argoroots** [comment]
done

**Comment by oksks** [comment]
Tested, confirmed.
