### ISSUE TITLE
BUG: Missing icons on DDA page

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#362]
**Describe the bug**

DDA's event page https://citizenos.com/dda and its subpages are missing icons in the right-hand side menu, which have been there all along:

<img width="349" alt="Screenshot 2023-01-11 at 23 54 48" src="https://user-images.githubusercontent.com/34126353/211926152-e1614fd4-be42-4518-9191-752d8c93e67f.png">

-----

It seems bulletpoints are also missing here, on the [Programme](https://citizenos.com/dda/programme) subpage, and also on the Application process page - likely the same problem:

<img width="700" alt="Screenshot 2023-01-11 at 23 58 05" src="https://user-images.githubusercontent.com/34126353/211926734-c7391cb0-232c-42c0-8b61-f27682ea472d.png">

**How critical is the bug?**
It's a huge and active event, so this needs to be fixed rather quickly.

**Comment by argoroots** [comment]
Done
