### ISSUE TITLE
BUG: News: headline + image issues

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#371]
**Describe the bug:**
1) I've created a new article, and for some reason, I can't get the header image to show up [here](https://citizenos.com/news/our-annual-report-2022), although it does show on the News frontpage. I replicated the previous (live) article's coding to the point, so can't pinpoint the error by myself.

2) Also, all headlines in all News articles have lost their formatting.

<img width="1272" alt="Screenshot 2023-01-21 at 23 44 12" src="https://user-images.githubusercontent.com/34126353/213888165-343b54e9-6ec8-4a8a-b324-39facf96d6df.png">

**Comment by argoroots** [comment]
fixed

**Comment by oksks** [comment]
Thanks @argoroots, confirming that it's solved, but what caused the issues?

**Comment by oksks** [comment]
@argoroots looking forward to your reply?

**Comment by oksks** [comment]
Fixed on the web 2.0
