### ISSUE TITLE
BUG: Annual report pdf doesn't open on MacOS Safari or Chrome

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#374]
**Describe the bug**

When the user goes to https://citizenos.com/news/our-annual-report-2022 and clicks on download report they are taken to

https://citizenos.com/assets/images/news/Citizen_OS_Annual_Report_2022.pdf 

which opens up a blank file (screenshot attached)
<img width="1405" alt="Screenshot 2023-01-31 at 15 54 31" src="https://user-images.githubusercontent.com/72747107/215780288-f96df8eb-ba2f-4dd4-bec9-a14fd9397237.png">

**How critical is the bug?**
People will not be able to access the report from the website OR social media (which links to the report above).

**To Reproduce**
1. Go to https://citizenos.com/news/our-annual-report-2022
2. Click on https://citizenos.com/assets/images/news/Citizen_OS_Annual_Report_2022.pdf 
3. See error

**Expected behavior**
Report should load content 

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS Chrome
 - MacOS Safari

**Mobile**
 - iPad OS

**Additional context**

**Comment by oksks** [comment]
Fixed last week
