### ISSUE TITLE
TASK: Please add "Vabaühenduste eetikakoodeks" on our website

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-web#375]
**What needs to be done?**
For applying funding from KÜSK, they require that on our website would be a reference to code of ethics of non-governmental organizations. Please add it on our website under "Meist" or "About us" following text:
Citizen OS järgib oma tegevustes vabaühenduste eetilisi põhimõtteid, mis on välja toodud Hea Kodanik veebilehel: https://heakodanik.ee/vabauhenduste-eetikakoodeks/

**Location**
Please add it here: https://citizenos.com/et/meist/

**Any additional files or info needed?**
We don´t need separate chunk for that. Please just mention that we follow the code of ethics.

**Deadline**
It´s rather urgent, as currently KÜSK will check if we meet the project requirements (and this is one of their requirements). Latest it should be on our website by 9.02.2023.

**Comment by oksks** [comment]
Done. I've placed the text in the main body of text and as our source language is English, I've posted it as:
>"Citizen OS adheres to ethical principles for NGOs, as outlined on the Hea Kodanik (The Good Citizen) website". 

Will add Estonian translation as soon as the change is synced to Crowdin, ~10mins or so.
