### ISSUE TITLE
TASK: Team page update (Indonesia)

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#379]
**What needs to be done?**
Agustina asked to add 4 core members of Indonesian team to our Team page.

- Tasia Rosalina Tedjo Purnomo, Marketing Manager for Citizen OS Indonesia
- Leony Chrisanti, Visual Designer for Citizen OS Indonesia
- Ivana Rahmania Widyaningrum, Program Manager for Citizen OS Indonesia
- Leo Zulfikar, Finance for Citizen OS Indonesia

**Location**
https://citizenos.com/team/

-----
**Any additional files or info needed?**

@Agustinaiskandar, could you please provide the following info:

1) their photos (2 for each person - see examples https://citizenos.com/team - add to Drive, please)
2) their email address 
3) their Linkedin URL

**Comment by oksks** [comment]
@Agustinaiskandar, here's a reminder to submit your team's info :)

**Comment by Agustinaiskandar** [comment]
Dear Oks, 

Please find the link below:

1. Tasia Rosalina Tedjo Purnomo, Marketing Manager for Citizen OS Indonesia
               Tasia said, her information is the same as what we have now on the website. Do you still need her pictures?
2. Leony Chrisanti, Visual Designer for Citizen OS Indonesia
               Photo: https://drive.google.com/drive/folders/1Ljb7sRWBdg5YhsDrAfgsCsNjE3P-jzh0?usp=sharing
               Email:  [leonychrisanti.work@gmail.com](mailto:leonychrisanti.work@gmail.com)
               LinkedIn: [linkedin.com/in/leonychrisanti](https://www.linkedin.com/in/leonychrisanti)
3. Ivana Rahmania Widyaningrum, Program Manager for Citizen OS Indonesia
               Photo : https://drive.google.com/drive/folders/1E3rrixIyEuPRFQuebdQdFn10GmEkGnmu?usp=sharing
               Email : [ikuu713@gmail.com](mailto:ikuu713@gmail.com)
               Linkedin : https://www.linkedin.com/in/iku-vana
4. Leo Zulfikar, Finance for Citizen OS Indonesia
               Photo: https://drive.google.com/drive/folders/1-272XQWZ3gvmngoTm8KTnIS3hHfqmiV6
               LinkedIn : https://www.linkedin.com/in/yoszulfikar
               Email : [Yoszulfikar@gmail.com](mailto:Yoszulfikar@gmail.com)


Thank you,
Agustina

**Comment by oksks** [comment]
Page updated, thanks @Agustinaiskandar! 
https://citizenos.com/team
