### ISSUE TITLE
BUG: Help Centre headings not displaying correctly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#391]
@oksks I noticed that the headings on the website version of the Help Centre are all displaying in the largest heading size: 

![image](https://user-images.githubusercontent.com/61320526/220373834-bf0bf7f5-d12c-4c21-ab93-18f18270013b.png)

Whereas on the Figma design (and in my memory how it was previously on the live version), it is like this (please ignore the pink line, not relevant): 

![image](https://user-images.githubusercontent.com/61320526/220373301-9a36e238-ef9c-4ca1-be8b-8e26f2a064b8.png)

And I see now that the same thing has happened on the platform version of the HC too. It should look like this: 
![image](https://user-images.githubusercontent.com/61320526/220374390-295e6afe-7dfe-4281-b61c-00dd5d3e704b.png)

But instead all the sub-headings are as large as the main heading: 
![image](https://user-images.githubusercontent.com/61320526/220374591-82770f2b-2860-4a76-b2b8-9cd69ec42474.png)

**Comment by oksks** [comment]
This one, I think https://github.com/citizenos/citizenos-web/commit/1b5e00096aa9e0442a22b83d5525dc631c889790

**Comment by oksks** [comment]
@argoroots here's a task for you.

**Comment by oksks** [comment]
Obsolete as of web 2.0 HC remake
