### ISSUE TITLE
TASK: Add an interview to the news section ENG + EST

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-web#404]
**What needs to be done?**
Please add an interview in English and Estonian to the news section about new team member joining Citizen OS.

**Location**
https://citizenos.com/news/
https://citizenos.com/et/uudised/

**Any additional files or info needed?**
Links to the news in EST(https://docs.google.com/document/d/1_Gs4p7GmLr5ZVEPGmR3Jt0aGtwMqXQqf_1kPjwRGTqs/edit?usp=sharing) & ENG (https://docs.google.com/document/d/1aCQW_ZLRoiU_swpBPy-POilkE59vlWu_Xz41K5rEPaI/edit?usp=sharing). 
Photo: used for both stories: https://drive.google.com/file/d/1bwDZXMr-wC7motacnlYymSuNcOW_P53g/view?usp=sharing

@oksks 

**Deadline**
6.03.2023

**Comment by oksks** [comment]
Done @MeelikaH! https://citizenos.com/et/uudised/ 
Awesome job placing your first article order - everything was clear and actionable. If you'd like to add keywords for SEO next time, please list them, too.
