### ISSUE TITLE
Remove breadcrumbs navigation from HC platform version (but not from website version)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#423]
@ilmartyrk are you able to remove the breadcrumbs from the platform version, or how can this be arranged? As per Kevin's previous input they are only needed on the website version of the HC, and are adding unnecessary clutter on the platform version.. 

![image](https://user-images.githubusercontent.com/61320526/227212746-6f2431c0-51af-410d-89ed-ecb96b957429.png)

_Originally posted by @BeccaMelhuish in https://github.com/citizenos/citizenos-web/issues/309#issuecomment-1481159670_

**Comment by oksks** [comment]
@argoroots could you please do this?

**Comment by oksks** [comment]
@devosama1 could you please resolve this as well?

**Comment by devosama1** [comment]
@oksks as i found out that the app is using Iframe to render from the website, there is currently no ability to render the helpcenter seperatly, either on website and app. And the new website is using the new breadcrumb which is not like this will show up on the app as well. 

@ilmartyrk you can try putting beta.citizenos.com/help on the iframe on test link and attach a screenshot here or a link to preview. I can further do adjustments as needed :) 

Adjustments are easy can be managed through Elementor inside the website @oksks (It will have the same effect)

**Comment by devosama1** [comment]
This task has been completed.

I have used shortcodes to display breadcrumbs and hidden breadcrumbs on the website and shown when its loaded inside an iframe. Also the header and footer is hidden when shown inside iframe (currently iframe is the option which shows helpcenter in the sidebar in app.citizenos.com)
