### ISSUE TITLE
PAGE: News section redesign

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#425]
**What needs to be done and why?**
It's time to refresh the design of the News page and its subpages, to align with the app's new design and the rest of the website.

1) Please provide a design update for the News page 
2) A banner for the frontpage, which would allow us to highlight a piece of news we really want people to see, or announce something
3) Design update for the article page in News section
---
**Needs for the article page (screenshots are only to illustrate the idea, not to be taken as a requirement :D):**
We wouldn't of course be using all of the following features at once, but want to have the option to embed them when necessary.

- A default footer, distinguishable from the rest of the content, for more information, author biography, or smth similar. 
![Screenshot 2023-03-27 at 15 19 16](https://user-images.githubusercontent.com/34126353/227939921-92239cbc-5710-44b5-a706-a4fff4fcc480.png)

- A "highlight" section within the article, with a quote from the text

- An optional CTA button within the article, to be placed in the middle or end of an article, leading to a reg form, questionnaire, or some other URL. Ideally, 2 options: 1) with a small summary next to the button, 2) just a catchy button to be placed at the beginning or end of the article.
<img width="474" alt="Screenshot 2023-03-27 at 15 27 31" src="https://user-images.githubusercontent.com/34126353/227941337-715a6528-3c4b-4407-b18d-02f57c862d74.png">

- An embedded video within the article (Youtube/Vimeo)
![Screenshot 2023-03-27 at 15 17 35](https://user-images.githubusercontent.com/34126353/227940055-12702a94-d043-460c-97b4-3017ff3cbf5d.png)
- An embedded gallery with a description underneath (photographer's name + theme of the gallery)
<img width="684" alt="Screenshot 2023-03-27 at 15 02 41" src="https://user-images.githubusercontent.com/34126353/227940035-ea5c59c2-5445-42cc-b389-54aa872bec04.png">

- "You may also like" section underneath the article, with maybe 3 articles.
---
**Location**
https://citizenos.com/news/
https://citizenos.com/news/how-to-encourage-better-political-discussions-during-elections

**Deadline**
April 6, if possible.

**Comment by kevincrepin** [comment]
Updates! Let me know if anything is missed.

**Homepage**

Desktop: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=1127-4370&viewport=818%2C-511%2C0.25&scaling=min-zoom&starting-point-node-id=1127%3A4370

Tablet: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=1448-8525&viewport=818%2C-511%2C0.25&scaling=min-zoom&starting-point-node-id=1127%3A4370

Mobile: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=1144-8823&viewport=818%2C-511%2C0.25&scaling=min-zoom&starting-point-node-id=1127%3A4370


**News List**

Desktop: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=2577-10703&viewport=818%2C-511%2C0.25&scaling=min-zoom&starting-point-node-id=1127%3A4370

Tablet: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=2585-12129&viewport=818%2C-511%2C0.25&scaling=min-zoom&starting-point-node-id=1127%3A4370

Mobile: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=2582-13501&viewport=818%2C-511%2C0.25&scaling=min-zoom&starting-point-node-id=1127%3A4370


**Article**

Desktop: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=2580-12182&viewport=-21170%2C-3199%2C1&scaling=min-zoom&starting-point-node-id=1127%3A4370

Tablet: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=2585-13542&viewport=-21170%2C-3199%2C1&scaling=min-zoom&starting-point-node-id=1127%3A4370

Mobile: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=2582-15067&viewport=-21170%2C-3199%2C1&scaling=min-zoom&starting-point-node-id=1127%3A4370

**Comment by oksks** [comment]
Thank you @kevincrepin!!
- Homepage banner - looks great, but the button would lead to the News page? Not the article itself? I’d expect it to lead to the article, I think. Good thing there's a link to the News page within the article now, so users would have a way to find it from the article view.
- Banner button looks to me a bit weirdly positioned in the Tablet view - I don’t have an improvement suggestion though, sorry. I feel like it shouldn’t sit lower than the bottom of the photo. But I do understand there’s a lot of text in the headline, and there might be an even longer one :(
- News homepage looks great!
- Article page also looks amazing! One thing I forgot to request, sorry - could you pls also add a subheading somewhere, to be able to structure the text better at times?

@MeelikaH could you pls also take a look at the designs and see if there's anything I've missed or you'd like to add? As soon as you're happy with everything, could you please assign the ticket to Osama, so that he could start developing the section on the new platform.

**Comment by kevincrepin** [comment]
Totally agree on the tablet banner. Tried different layouts and this one still came out as the better one... :D Maybe we can remove the image here? 
![Screenshot 2023-04-06 at 10 28 35](https://user-images.githubusercontent.com/26792281/230305989-5402078d-f886-4167-befe-cc365398cf8c.png)

We can have either the button leading to the article or we can make the article title clickable and have the button lead to all news. Both ways are possible.

**Comment by MeelikaH** [comment]
I will give my feedback but due other tasks and commitments, I will be reviewing and forming my ideas during the second half of the next week.

**Comment by kevincrepin** [comment]
Made some updates!

- Homepage has bigger News section now
- News items have a read more link, but should be entirely clickable (hover state can be checked here: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=2577-10703&viewport=-1589%2C-53%2C0.13&scaling=min-zoom)
- There's a pinned/highlighted news item now
- There's also a subheading style added to the article
- I think for smaller screens where the tabs don't fit anymore the dropdown still makes sense. Not sure if a filter icon would actually make it clearer that it's clickable than an arrow? Open to other opinions!

Homepage link has changed: https://www.figma.com/file/eHBSunqUv10fMcWmiEEXiv/Website?node-id=2651%3A12540&t=undOh5YSZjauU1D6-1
But others should still be the same.

**Comment by BeccaMelhuish** [comment]
@MeelikaH @kevincrepin @oksks, adding my thoughts as requested :) 

*Homepage news section looks much better like this :) I do have a doubt as to whether it should be right at the top like that, but I think it's OK. 
*I'm struggling a bit with the fact that the news items are now both fully clickable overall and also have a "read more" button. I feel like it being entirely clickable makes the read more button redundant, as clicking either on or off the "read more" makes no difference.. Could it be just either (1) entirely clickable, or (2) clickable title and photo (with clickable "read more" if it's felt necessary to add that too, but maybe just adds some "clutter").
*Will there be a "load more stories" or something at the end of the the news stories that first show up? 

That's it from me though, otherwise all is looking great - especially love the article page!

**Comment by kevincrepin** [comment]
_*I'm struggling a bit with the fact that the news items are now both fully clickable overall and also have a "read more" button. I feel like it being entirely clickable makes the read more button redundant, as clicking either on or off the "read more" makes no difference.. Could it be just either (1) entirely clickable, or (2) clickable title and photo (with clickable "read more" if it's felt necessary to add that too, but maybe just adds some "clutter")._

I don't really think it's an issue, because the fact that it's entirely clickable is only known once user hovers over it. And the read more triggers this kind of action. Also on mobile and touch devices there's no hover possibility and we stil lwant to make it clear that they're clickable. I'd say this covers most scenarios.

_*Will there be a "load more stories" or something at the end of the the news stories that first show up?_
Yes! Will still add this (or pagination)

**Comment by oksks** [comment]
Heya,
Glad you guys have been honing the designs - looking great!

+100 to the same doubt as @BeccaMelhuish expressed - I do understand that having a News block on the frontpage can show us as an active and "alive" organization with much to give, but would place it lower down the page, as otherwise, it will take the visitors away from the main task of the page, which is to introduce the organization and our platform.
---
Having also just received @anettlinno's comment on the topic in Slack as she's the content owner - yup, let's move it down the page. 
@kevincrepin, I personally would place it right above the stats, but am very much looking forward to your proposal as to where it makes the most sense to be placed, considering our current content and focus.

**Comment by oksks** [comment]
Thanks @kevincrepin! @devosama1 is implementing the updates on the Beta page as we speak, so I'm closing the ticket.
