### ISSUE TITLE
TASK: Options menu icon for Help Centre 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#445]
Would be useful to have an icon that could be inserted into texts that talk about the options menu on mobile. 

For example, here (HC topic below), it would be useful to have the hammer icon from mobile topic view (ideally exactly the same one): 
![image](https://user-images.githubusercontent.com/61320526/236856712-37cc9f9c-e611-4e89-b7b1-98da7830a2df.png)
 
![image](https://user-images.githubusercontent.com/61320526/236853973-cf4bc8a6-db03-4ac2-86eb-c4ae44ac6ba1.png)

Once this icon is given to @oksks in a way that can be easily inserted into the texts, I can let her know which HC texts to add them to. 

(I think this is the only such icon we need, currently).

**Comment by oksks** [comment]
@BeccaMelhuish we no longer develop the old platform with Argo.
@devosama1 - could you please advise, how could we implement an in-line tiny image in HC section in Elementor, so that it wouldn't butcher the rest of the text?

**Comment by devosama1** [comment]
Hi @oksks 
There are multiple ways to add it. I will try to go one by one.
So esentially, when you are adding text in Elementor, you are using a WISYWIG editor to add details and it allows code insertion, image, links etc. so we have multiple options. 
Using this code piece inline with the text <img src='/wp-content/uploads/2023/05/gavel-icon.svg' style="height:1rem;"></img> will allow the icon to be added to the text. 

![image](https://github.com/citizenos/citizenos-web/assets/56334857/7d9b7f56-411b-4d4a-8d49-db5af61d1e59)

**Comment by oksks** [comment]
Thank you!
@BeccaMelhuish - let's then wait until HC is launched on the new platform, if that's OK :)

**Comment by BeccaMelhuish** [comment]
Super yes sounds good to me, thanks both!!

**Comment by oksks** [comment]
Hey @BeccaMelhuish, would this work? I couldn't find exactly the same icon (pls send it to me if you have it in SVG, I can use whichever image), but it's pretty similar and I can add it anywhere:

![Screenshot 2023-06-26 at 14 44 50](https://github.com/citizenos/citizenos-web/assets/34126353/54a86469-d02a-4a86-9072-ff043ef87ec1)

(Icon size 13px x 13px for future reference)
If it works for you, lmk in this same ticket where you'd like it placed, please.

**Comment by BeccaMelhuish** [comment]
Hey @oksks sorry for slow reply - I'm thinking now that I am focusing on preparing the new HC texts for the redesign rather than improving the current platform's HC, let's put this on hold for now. But I will have a similar request for using icons from the redesign in similar way. Will send a list soon of icons that it would be good to use from there :)

**Comment by oksks** [comment]
Ok thanks, then closing this ask.
