### ISSUE TITLE
TASK: Update DDA Programme Page

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#446]
**What needs to be done?**
In the DDA programme page under the Implementation phase (https://citizenos.com/dda/programme) all the dates 

need to be replaced with 

- Mentoring session (dates and time to be agreed with the mentor)

- Wed 31 May | Training Session

- Mentoring session (dates and time to be agreed with the mentor)

- Wed 14 June  | Training Session

- Mentoring session (dates and time to be agreed with the mentor)

- Wed 5 July  | Training Session

- Mentoring session (dates and time to be agreed with the mentor)

- Wed 9 August | Training Session

- Mentoring session (dates and time to be agreed with the mentor)

- Wed 23 August | Training Session

**Location**
https://citizenos.com/dda/programme 

Under Phase III Implementation

**Any additional files or info needed?**

Where the dates need to be replaced

<img width="1350" alt="Screenshot 2023-05-09 at 20 17 52" src="https://github.com/citizenos/citizenos-web/assets/72747107/0cf3ba42-b976-4437-b13c-009d827e73d5">
<img width="1350" alt="Screenshot 2023-05-09 at 20 18 00" src="https://github.com/citizenos/citizenos-web/assets/72747107/071c7527-4131-419a-8fb1-b75c495c2c56">

**Deadline**
13.05.23

**Comment by oksks** [comment]
Done! :)
