### ISSUE TITLE
TASK: Publishing two articles (ENG page)

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-web#456]
**What needs to be done?**
@oksks please publish two articles on our English language news page. When the articles are live, please notify me on WhatsApp as I'm out of office (A).

**Location**
https://citizenos.com/news/

**Any additional files or info needed?**
First article for publishing can be found here: https://docs.google.com/document/d/1eTiGjDKYNmKP6xfqLaVvgYiaVwIbYIMfXIDCWiOLSDw/edit?usp=sharing

Second article for publishing can be found here: https://docs.google.com/document/d/1agVc0oM0zeziLi2WDuHRPG7Kp26HxhcO1JxXAG5Wx8Q/edit?usp=sharing

NB! The articles will be referring to one another. Linking one to another is needed. Photos to be used have been added to the file.

Thanks a million!

**Deadline**
Ideally 19th of May, but 22nd of May 21:00, the latest.

**Comment by oksks** [comment]
@MeelikaH 
Articles are live, please check them at https://citizenos.com/news/. 
We currently don't have subheadings nor a quote feature in the News section, but they will be in the new web CMS. 

Pls let me know in Slack, if anything needs to be updated!
