### ISSUE TITLE
TASK: Publishing an article on the Citizen OS website, news section

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-web#462]
**What needs to be done?**
@oksks , please publish an article on the website (ENG, news section).

**Location**
https://citizenos.com/news/

**Any additional files or info needed?**
Text with guidelines and links to the photos can be found here: https://docs.google.com/document/d/1NYhLCksaDW8j9eldd-HHjFd_KQnKyGdZCGc7KFlOlho/edit?usp=sharing
The text and guidelines have been added based on the revamped news design.

**Deadline**
14.06.2023

**Comment by oksks** [comment]
Done
