### ISSUE TITLE
TASK: A generic image for HC category sections

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#463]
**What needs to be done?**
We don't have videos for the Help Center categories yet, so would need to add a generic illustration for now, to replace these.
![Screenshot 2023-06-08 at 10 43 06](https://github.com/citizenos/citizenos-web/assets/34126353/ea405e21-3ded-4bc5-9ab7-eb6c39b5a7c3)

Categories, which would host the image, are:
<img width="1070" alt="Screenshot 2023-06-08 at 10 44 35" src="https://github.com/citizenos/citizenos-web/assets/34126353/0fef9316-d0a2-47c8-bda5-2edf25cc9e45">

**Location**
For example, https://citizenos.com/help/login

**Deadline**
Next week - June 13th?

**Comment by kevincrepin** [comment]
Let's use the same as we (should) have on the homepage ;)
https://www.figma.com/file/eHBSunqUv10fMcWmiEEXiv/Website?type=design&node-id=118%3A1546&t=i5Z1LoRvkrojHudX-1
