### ISSUE TITLE
TASK: Help Centre pre-launch requirements

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#464]
**What needs to be done?**
List of things to solve in the new HC prior to web 2.0 launch, apart from the other HC tickets, according to how it looks in Figma.
NB! Ticket is WIP and gets updated with any new issues I find. Please tick the ones that are fixed :) 

- [ ] Reduce padding between the text and the entry field
<img width="1324" alt="Screenshot 2023-06-08 at 10 35 52" src="https://github.com/citizenos/citizenos-web/assets/34126353/37f39e64-533b-43af-ad4c-530f95c5bd69">

- [ ]  Change footer's default text "Alternatively try these options" to "Contact us", as that's what it essentially is, and sounds less clunky
- [ ]  Fix links in Help Centre main page
- [ ]  Fix padding on http://beta.citizenos.com/?s=vote according to Figma
- [ ]  Remove Help link from the top navigation (under News)
- [ ]  Sync link font sizes 
<img width="1146" alt="Screenshot 2023-06-12 at 10 17 28" src="https://github.com/citizenos/citizenos-web/assets/34126353/3a178d07-624d-4cf8-8693-ebf49fcaf97d">
- [ ]

**Comment by devosama1** [comment]
@oksks All done above
