### ISSUE TITLE
TASK: Publish a story on the News section of Citizen OS website

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-web#466]
**What needs to be done?**
@oksks please publish a a story on our News section. 

**Location**
https://citizenos.com/news/

**Any additional files or info needed?**
Text and photos are all in this file: https://docs.google.com/document/d/1PNESxCnRDi26TEWedG50LUQ6W2ZEjx6oTPeySO0NrgM/edit?usp=sharing 

**Deadline**
By 03.07.2023 9:00 AM (but no sooner than 29.06.2023)

**Comment by oksks** [comment]
Please add the file :) @MeelikaH
