### ISSUE TITLE
BUG: Fonts and colours 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#467]
**Describe the bug**
The font is not correct (Noto Sans JP) on a few pages

1. https://beta.citizenos.com/
2. https://beta.citizenos.com/team
3. https://beta.citizenos.com/news/
4. https://beta.citizenos.com/vision/

Two examples added below. Also in the examples added below, I am not sure if the colour grey was meant to be used here. Tagging @kevincrepin for input.

![IMG_0480](https://github.com/citizenos/citizenos-web/assets/72747107/d7846eb6-bace-4767-951b-132fa5b60cea)

![IMG_0479](https://github.com/citizenos/citizenos-web/assets/72747107/87e982df-0b3d-4de3-ab91-135cc15e8325)

**How critical is the bug?**
Quite critical as the fonts and colours need to be consistent for branding and marketing purposes 

**Smartphone (please complete the following information):**
 - Device: Mobile/Tablet 
 - OS: iPad, iOS, Android 
 - Browser: Safari and Chrome

**Comment by oksks** [comment]
@ssin1901 thanks for catching it! I just checked Figma, our default font should be **Noto Sans**, not **Noto Sans JP** unless I'm missing something. But we will go through all sections and make sure they're all Noto Sans.

**Comment by oksks** [comment]
And confirming that the grey paragraph colour is actually implemented according to Figma, I just checked.

**Comment by ssin1901** [comment]
@oksks you are 100% right. Also checked the CVI. My apologies.

**Comment by oksks** [comment]
Done! Thanks for catching it <3
