### ISSUE TITLE
BUG: Spacing issues 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#468]
**Describe the bug**
On the landing page there is a bit too much spacing between 2 sections (screenshots below). 

![Screenshot 2023-06-26 at 11 36 43](https://github.com/citizenos/citizenos-web/assets/72747107/0ff0b190-852f-4ecc-8a42-d276e1d9444c)

![Screenshot 2023-06-26 at 11 36 27](https://github.com/citizenos/citizenos-web/assets/72747107/beb4ed63-bd9c-4c2b-9100-9ce3f88adaac)

**How critical is the bug?**
In mobile view, the space looks very odd and may lead the user to scroll away thinking the page is broken 

**To Reproduce**
1. Go to https://beta.citizenos.com 
2. Scroll down 

**Expected behavior**
Maybe spacing needs to be adjusted @BeccaMelhuish @kevincrepin 

**Smartphone (please complete the following information):**
 - Device: Mobile, Tablet  
 - OS: iPad, iOS, Android 
 - Browser: Safari, Chrome

**Comment by devosama1** [comment]
This is resolved by adding a 50px spacer within the drag and drop blocks

**Comment by oksks** [comment]
Done
