### ISSUE TITLE
BUG: Dead links 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#469]
**Describe the bug**
Dead links in the following places

1. Margo Loor LinkedIn (Page not found)
2. Kati Vellak LinkedIn (Page not found)

**How critical is the bug?**
Moderate 

**To Reproduce**
1. Go to https://beta.citizenos.com/team
2. Scroll down to profiles 

**Expected behavior**
All links should work

**Comment by oksks** [comment]
Thanks @ssin1901!! Margo seems to have changed his profile URL during the last week, and Kati to have deleted her LinkedIn profile also during the last week 🤔 
Fixed.
