### ISSUE TITLE
TASK: Google Translate option

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#470]
**What needs to be done?**
We've decided to pause professional translations of the website for now, and have integrated a Google Translate button to the top navigation instead. 
We might need a better design/placement for it, as per @BeccaMelhuish's comment:

"...This looks very odd and out of place to me, I thought it was a loading error. I’d suggest the globe icon we have on the current page, or maybe Kevin can help with a better solution :) "

![Screenshot 2023-06-26 at 14 15 27](https://github.com/citizenos/citizenos-web/assets/34126353/2a9af2c1-abb4-40c7-b0f0-06040007d2c0)

**Location**
https://beta.citizenos.com/

**Deadline**
A week from now? Monday July 3?

**Comment by kevincrepin** [comment]
I agree it's a bit confusing because either the lack of label or a clearer icon. I would say with a label is the clearest but it also takes up more space.

![Screenshot 2023-07-04 at 12 07 08](https://github.com/citizenos/citizenos-web/assets/26792281/0ba5e9e7-9ad2-4f2b-8ecc-6ff3d27f81dc)

**Comment by devosama1** [comment]
@kevincrepin I added a popover the icon with some text for clearer direction. Any advice on that? Otherwise i can change to this :) thanks

**Comment by oksks** [comment]
Looks good to me, do you agree @kevincrepin?

**Comment by kevincrepin** [comment]
On touch devices this wouldn't work I'm afraid, so there we'd need to have the label visible by default. And at that point it's kinda why not also show it immediately for the desktop.

**Comment by BeccaMelhuish** [comment]
Just to give my two-pence, for me this icon is way preferable in terms of the look and feel - visually the blue Google icon just looks really out of place to me.. (Hence my initial comment re thinking it was an error). 

![image](https://github.com/citizenos/citizenos-web/assets/61320526/aacb3c1d-96b6-432f-ad5f-84236cc410c5)

**Comment by oksks** [comment]
@BeccaMelhuish, I agree it's a better icon and also universally understood by users across the world, but I couldn't for the life of me figure out how to make sure users understand they'll be using machine translation option to see the page in their language - and we 100% have to be sure they are aware of that, as expectations to professional translation are totally different.

@kevincrepin wdyt?

**Comment by BeccaMelhuish** [comment]
@oksks Ah I see! 
I feel like it's OK though as it comes up like this when you click on it, so should be clear it's Google? 
![image](https://github.com/citizenos/citizenos-web/assets/61320526/98c257b2-c540-45c7-b524-7e44a4ac6fdb)

**Comment by oksks** [comment]
@devosama1 let's please change the icon to the small globe one :)

**Comment by devosama1** [comment]
Updated the icon to globe.
