### ISSUE TITLE
BUG: Space between paragraphs 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#471]
**Describe the bug**
Should be space between paragraphs here (screenshot attached)

![Screenshot 2023-06-26 at 14 32 08](https://github.com/citizenos/citizenos-web/assets/72747107/76727f6a-2fad-4eb5-b74f-5b6a2e564674)

**How critical is the bug?**
Describe the severity of the bug's impact.

**To Reproduce**
1. Go to https://beta.citizenos.com/careers/
2. Scroll down 

**Expected behavior**
Spacing between paragraphs should be consistent

**Smartphone (please complete the following information):**
 - Device: Mobile, Tablet 
 - OS: iPad, iOS, Android 
 - Browser: Safari, Chrome

**Comment by oksks** [comment]
Fixed, thanks!
