### ISSUE TITLE
BUG: Stats 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#472]
**Describe the bug**
@oksks @devosama1 we agreed here #358  that we will not include the Rahvalgaatus statistics. 

It was done previously but I think currently the Rahvalgaatus stats are included.

![Screenshot 2023-06-26 at 11 36 59](https://github.com/citizenos/citizenos-web/assets/72747107/9a7c554c-78e2-4b39-882e-ffd2f456282f)

**How critical is the bug?**
To my mind, it is not the end of the world as we are a transparent organisation and can always explain why the Stats changed. 

Ideally should be rectified before the launch though. 

**To Reproduce**
1. Go to https://beta.citizenos.com 
2. Scroll down to the bottom 

**Expected behavior**
Refer to #358 

**Smartphone (please complete the following information):**
 - Device: Mobile, Tablet 
 - OS: iOS, Android 
 - Browser: Safari, Chrome

**Comment by devosama1** [comment]
Currently integrated into the WEB 2.0. 

This feature is custom coded inside website as a shortcode in the child theme folder inside /includes/shortcodes.php

the data is fetched from https://api.citizenos.com/api/stats and you can get specific stats by using the following shortcodes 
[rahvaalgatus_stats category="discussions"]
[rahvaalgatus_stats category="votes"]
[rahvaalgatus_stats category="groups"]
[rahvaalgatus_stats category="users"]

Each shortcode returns specific data from the API, ready to be used anywhere on the wordpress website. 

If you like to show this data inside some text you can simply put this inside the editor with the brackets and update the content. It is preferred that this shortcode is added not in the visual option of the editor, but the text option in the editor. The text options shows the html of the content that is being injected into the website. 

Also you have code blocks and shortcode blocks in the Elementor builder. You can use those and add.

Task complete @oksks @ssin1901 

![image](https://github.com/citizenos/citizenos-web/assets/56334857/d35eb480-cb5d-4c73-a67e-f10dc33cc2f8)
