### ISSUE TITLE
BUG: Winter and Summer Schools should be changed to just Summer School 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#473]
**Describe the bug**

On https://citizenos.com/projects/ if you go to Load More you find a project titled Winter and Summer School with Tallinn University. This should be corrected to only Winter School (screenshot attached)

![Projects - CitizenOS](https://github.com/citizenos/citizenos-web/assets/72747107/3393de8a-ae1f-425c-b033-5455ddf38205)

**How critical is the bug?**
Should be fixed as soon as possible as it might confuse the users

**To Reproduce**
1. Go to https://citizenos.com/projects
2. Scroll down the page
3. Click on Load More 
4. See Summer and Winter School 

**Expected behavior**
Should only say Winter School 

**Screenshots**

**Comment by devosama1** [comment]
Title and slug changed to winter school. Also added a 301 redirect to https://winterschool.tlu.ee/digital-innovation-for-civic-engagement-projects/ for SEO reasons. Example, if google scans the article and shows from the website, the article will redirect to original link where intended to go. 

**For future: External project links must be added at 2 places, one inside project edit page, and at 301 redirect option.**  @oksks 

![image](https://github.com/citizenos/citizenos-web/assets/56334857/0b7ed55a-e883-4940-bf15-10912edde771)
![image](https://github.com/citizenos/citizenos-web/assets/56334857/d4f005d9-d9a8-45d4-8236-62c76e883ecd)
![image](https://github.com/citizenos/citizenos-web/assets/56334857/af716468-ac57-449b-b08e-af60dd497878)

Task resolved @ssin1901
