### ISSUE TITLE
TASK: Text and layout updates to landing page

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#476]
@oksks @devosama1 @anettlinno 

As per @MeelikaH's Slack message, we now have the final texts and layout decisions for the landing page! Hooray. 

So here are the new texts for each chunk:
https://docs.google.com/document/d/1MCw_0hLf_wPihmvt5NP_rlzqtEh5HVG7qe-jc86omow/edit?usp=sharing 

Based on user feedback, the News chunk should be Chunk 5, as per the document. (Thank you Oks for the popular suggestion!). 

Most of this should be a simple copy-paste job, but I've marked with comments in the doc three places where there will need to be diversion from the existing design in order to accommodate the new texts. @devosama1 - would you be able to see what you can do with what we have already? As agreed in the MM I can give input from a design perspective, then if we need Kevin's input when he's back from holiday we can ask for it :)  

Deadline: What's reasonable? End of the month? Depends on your workload/holiday, etc.

**Comment by BeccaMelhuish** [comment]
@devosama1 I just saw that Meelika suggested a deadline of 3rd August (next Thursday) for getting all this sorted, what do you think - does that seem reasonable for your side of it (allowing time for some back and forth with designs)? 

(Though presumably will depend on when @oksks is back from leave to switch over the texts, or me/Meelika could presumably do this if she's swamped on return!)

**Comment by BeccaMelhuish** [comment]
@oksks and @MeelikaH, Osama and I met yesterday to make progress on this, here are the notes  so you know where we're at and can input as you wish :)  

- Chunks now re-ordered and most of the design requests done (in draft). Will ask Kevin to give it a look over once finished and see if he has any requests/suggestions for the design changes.  (We can make it live once we are happy though, then make any changes if necessary). 
- I will post in this thread soon to let @devosama1 know which 5 icons to use for the "Who we're here for" section. 
- @devosama1 will add a background to the news chunk. Could we see how yellow looks? 
- @devosama1 suggested a slider of product images rather than the illustration next to "Our platform" and I agree the illustration is maybe not the best there - it gives quite "offline paper filing" vibes to me, and makes sense to showcase the actual platform there (maybe once the new UX/UI is live though and looking beautiful). Or if we keep it illustrated, maybe we can switch to another. What are your thoughts @oksks and @MeelikaH?   
- I will make an issue to ask Kevin to consider how to amend the design to make the double CTA we want (to both platform and projects) work. For now we've just left it as it is (CTA to platform only).  
- Texts are not yet all inputted (a few headings changed etc, but mostly still old texts in there. We can add the texts ourselves and let Osama know when it's ready to launch or ask for other design changes if needed. This is the link to edit the draft page: https://citizenos.com/?page_id=6203 (Actually, seems this link doesn't work, but it's the draft called "Landing 2.0")

**Comment by BeccaMelhuish** [comment]
@devosama1 and @oksks, I just had a call with Meelika and she is on board with Osama's suggestion (as above) of replacing this illustration with a slider showing different aspects of the platform. So Oks if you are happy with this too then we could do so once we have the redesign launched :) 

And the uploading the new texts, we agreed I will do this.

**Comment by BeccaMelhuish** [comment]
Hi @devosama1 and @oksks I'll put the last outstanding tasks before this is ready to publish here, just so it's all in one place and you can both see what's what (instead of the separate Slack convos we were having) :) 

- The our "community is growing" heading is displaying bolder than the rest:
![image](https://github.com/citizenos/citizenos-web/assets/61320526/81684f50-2a9c-409e-b7dc-380f8bacfb6b)

- Could you make the "What we offer" intro blurb a bit narrower:
![image](https://github.com/citizenos/citizenos-web/assets/61320526/4337597b-5d8b-4057-9911-181f07a842d3)

- Could you make the "Who we're here for" intro also a little narrower so that "Sounds like" goes down to the next line?
![image](https://github.com/citizenos/citizenos-web/assets/61320526/d3231548-bb12-479a-8dfe-a87f37258667)

- For the News chunk background, please make it pale yellow

- These are the icons for the 5 target groups please: 
![image](https://github.com/citizenos/citizenos-web/assets/61320526/f8bcfdae-4ac6-4536-adb9-65090c141ce0)

Then I think we'll be good to make it live :D

**Comment by oksks** [comment]
Hey @BeccaMelhuish and @MeelikaH!
I absolutely agree, let's use the platform screenshots as soon as we have something to show. We've so far only used illustrations, as the current platform is way outdated.

**I've addressed the following issues:**

- Changed the heading so it is in line with the others now
- Made the "What we offer" blurb narrower
- Made the "Who we are" blurb so that "Sounds like" text is on a new line

**@devosama1, two asks for you:**
1) could you please make the News blurb background pale yellow?
2) could you please make sure the green statistics numbers stay green in live?

@BeccaMelhuish, could you pls provide the image files for the icons? Or you have already, somewhere? I'll be able to change them in the draft, then.

**Comment by BeccaMelhuish** [comment]
Thank you @oksks!

- For making the heading intros narrower, is it possible to bring the size of the box inwards rather than using line returns? As it means that at certain sizes it does this: 
![image](https://github.com/citizenos/citizenos-web/assets/61320526/13132ecc-9fd5-49d3-93b4-d3301a0d424d)
![image](https://github.com/citizenos/citizenos-web/assets/61320526/60c4f688-562e-40be-b991-6b1b6a637fd2)
Ideally it would be all one paragraph (no line returns) but with this text box made narrower: 
![image](https://github.com/citizenos/citizenos-web/assets/61320526/8be023a6-95ba-445b-a7b8-65f6cdd8e090)

- Something's up on the live version and a bit of the draft version has snuck into the middle of the old texts here, could it be removed until the new version is finalised? 

![image](https://github.com/citizenos/citizenos-web/assets/61320526/1f1fa5c9-7057-469e-adda-c65aa2e67f33)

- Looks like the green stats are OK now, they've been green every time I've looked lately :D 

- The icons are all from the pool of web icons/illustrations that Kevin put together, and 4 of those 5 are already on the live version - but the missing one is this heart attached. This is design file I use, is it in the right format for you?  

![heart](https://github.com/citizenos/citizenos-web/assets/61320526/54017928-1bbc-4b8a-9c91-a0d4b7819945)

**Comment by oksks** [comment]
Hey hey @BeccaMelhuish, I've updated the line returns and boxes are narrower than before by 120px from each side.

I've also removed the excessive box from "Who uses our platform?" bit - we need to be really careful not to mess up the live pages.

Just have added the heart icon to the Media Library on CMS - btw do you know what happened to the library? It looks like this 😆 

<img width="1439" alt="Screenshot 2023-08-10 at 22 56 58" src="https://github.com/citizenos/citizenos-web/assets/34126353/e629d8e0-ddd4-4473-b850-09f12ac038d4">

**Comment by BeccaMelhuish** [comment]
Super, thank you @oksks!

I've added the heart icon now. Hmm no, no idea what's up with the media library I'm afraid! Nor how the live version got an additional set of activists - I've only worked on the draft.. 

So now all that's outstanding is the background for the News page, but seeing as it's already missing on the live version I think we can publish it as it is in the meantime, so that the rest of the page is updated? 

And ideally if this box can be a little narrower so that "Sounds like" starts on the next line on desktop (but without a line break), would be perfect, but that's a minor tweak :) 

![image](https://github.com/citizenos/citizenos-web/assets/61320526/a89924d2-0fff-4e90-b84d-a8cb86f52e52)

Thanks a million!

**Comment by devosama1** [comment]
All finished for landing page :) live and draft

**Comment by oksks** [comment]
@BeccaMelhuish - the "no line break thing" is hard to implement, as all desktops have different screen sizes and inevitably it will not look the same on other screens :( 

Here's what it looks like on my screen (draft page) atm:
![Screenshot 2023-08-15 at 12 40 21](https://github.com/citizenos/citizenos-web/assets/34126353/2307931c-f392-4324-b524-6622a1d6bc2b)
