### ISSUE TITLE
TASK: British English for "Help Centre" in breadcrumbs navigation

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#477]
@devosama1 as per Slack convo, please change the breadcrumbs from Help Center to Help Cent**re**. 

![image](https://github.com/citizenos/citizenos-web/assets/61320526/959ed013-4512-4ce2-8ec7-823bd97b7990)

**Comment by devosama1** [comment]
Helpcenter text has been updated :)

![image](https://github.com/citizenos/citizenos-web/assets/56334857/70d9bb17-d987-48a7-a8c0-bcd38e18743c)
