### ISSUE TITLE
TASK: Formatting fixes for HC platform version

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#478]
@devosama1 I noticed some spacing issues on the HC platform issue:

Here is how it looks currently: 

![image](https://github.com/citizenos/citizenos-web/assets/61320526/d9be2236-6f5d-4a4f-a7b6-9f47dbbf8760)

And here is how it should be, in the design:

![image](https://github.com/citizenos/citizenos-web/assets/61320526/62666604-6180-45dd-8fe8-acd5a8ab56bc)

So there needs to be:

- Much less space above all main headings
- More space between letters in "HELP CENTRE" at the top

Thank you :)

**Comment by devosama1** [comment]
@BeccaMelhuish these are done as well.

**Comment by oksks** [comment]
Thanks @devosama1 - however it looks like there's still no intended spacing between the letters in the "HELP CENTRE" at the top? 

![366760825_1735504023589010_3501593623815407207_n](https://github.com/citizenos/citizenos-web/assets/34126353/b0c39f66-be32-4f54-8d00-fc98344a7ddc)

The other part of the task is fine, thank you.
EDIT: Sorry for the humongous image 😬

**Comment by devosama1** [comment]
@oksks I have pushed the code to add spacing. @ilmartyrk is there a caching for this? i can see the code in files but its not propagating to DOM.

**Comment by ilmartyrk** [comment]
@devosama1 I merged it into master  -  master branch is linked to our testing environment. For live we use prod branch, anyway just created a pull and it should appear in our live app

**Comment by oksks** [comment]
Tested, all good, thank you!
