### ISSUE TITLE
TASK: Double CTA design and edits check-over

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#480]
@kevincrepin We've made some changes to the [landing page](https://citizenos.com/) texts, and have two asks for you as a result:

1. Would you be able to have a quick look over the changes to the design that we've made and see if you are happy with how it's all currently looking, or suggest new designs for what we've done if you feel there's a better way of doing it? 

The main places the design has changed are here: 

Changing from 4 blocks to 5: 
![image](https://github.com/citizenos/citizenos-web/assets/61320526/2553a561-914f-4023-a01a-dfb652c0b1c4)

Adding in the top layer of stats: 
![image](https://github.com/citizenos/citizenos-web/assets/61320526/0d588a03-c44d-4103-bda4-b3fe757f4a7f)

2. For the CTA at the bottom, we'd ideally like a kind of "Double CTA". The background is that we've re-written the texts throughout the landing page to give more the impression that we are an organisation which has both civic engagement/training projects and also a platform, i.e. we're not just all about the platform. 

So ideally we would like to reflect this in the CTA at the end too if possible. (Like at the top, we now have buttons to both projects and platform). Would you be able to suggest a design for this? 

This is the copy we prepared for it, but you could adjust it if you feel it would work better written/structured differently: 

**Try our platform**
It’s free for everybody and for always! 
Use platform (button)

**Check out our projects**
We’re always looking for partners and participants
Projects (button)

Tagging @MeelikaH and @oksks so you're in the loop :)

**Comment by kevincrepin** [comment]
I think the stats are fine and below are some suggestions for the changes.

For who section:
Doesn't really work amazingly with 5 and in general I think the texts kinda start creeping into each other. At first I figured this would provide better balance (but it sacrifices readability a bit): 
![Personas_v1](https://github.com/citizenos/citizenos-web/assets/26792281/ee06cf95-bfc9-4d63-80f9-eb6e1ff231c6)

But then I tried this alternative and for me this works the best: very clear and easily readable. It takes up a bit (but only a bit) more space, but I think it's worth it for clarity:
![Personas_v2](https://github.com/citizenos/citizenos-web/assets/26792281/6446c207-3051-403b-a0c4-22b01ff99546)


For the double CTA it could be like this: 
![Screenshot 2023-08-16 at 17 02 18](https://github.com/citizenos/citizenos-web/assets/26792281/f257dd54-6ee8-4336-b46e-459352dcd2bf)

**Comment by BeccaMelhuish** [comment]
Wonderful, thank you @kevincrepin! 

@MeelikaH and @oksks what are your thoughts? 

My feelings: 

- The double CTA I think looks good and we could ask Osama to implement that already? 
- For the "who we're here for" the first option looks so much more beautiful, but I do see that the second one is much more likely to be read. 
- I just did a very quick mockup (attached below) using a previous mockup file (with some outdated designs but gives the gist) with the second one though, and I feel like it's not quite the right feel. Feels a bit too dry and unengaging.. Other than the  "blocky" layout, I think it might be the white backgrounds and small icons?  
- Also wondering if it's a bit too repetitive to have the vertical string of rectangles in that section, followed by the same (similar) layout with the platform features in the next one.  

[Who we're here for mockup.pdf](https://github.com/citizenos/citizenos-web/files/12366978/Who.we.re.here.for.mockup.pdf)

**Comment by oksks** [comment]
Thanks Kevin and Becca!
- I'm pro the double CTA - looks good, let's implement - will assign to @devosama1 
- Who we're here for - I agree, too many rectangles in a row screw up a beautiful page, too repetitive. 
Changed the layout in live - pls check: https://citizenos.com/. Looks alright imho, and works in mobile.

**Comment by kevincrepin** [comment]
Looks ok for me!

**Comment by devosama1** [comment]
2 templates ready to be used, named as below :)

Col1-Home-who-we-here-for 
Double CTA

You can preview the changes in Landing2.0 

@oksks

**Comment by BeccaMelhuish** [comment]
Thank you @devosama1!

No need for the "Who we're here for" as it was agreed we'll keep what Oks has done on the live page currently.

But for the Double CTA, looking good except a little less balanced than Kevin's design:

How it looks to me in the preview:
![image](https://github.com/citizenos/citizenos-web/assets/61320526/4f146c73-fdf7-48e7-801f-5ec34715c47b)

Kevin's design: 
![image](https://github.com/citizenos/citizenos-web/assets/61320526/a1afd9e3-c099-4f62-9e1c-44955c5cbd02)

(I think rocket man is probably fine where you have him though, but the rest could be balanced up :)) 

P.S. spacing between the text lines could be a bit tighter too, like in the design

**Comment by devosama1** [comment]
@BeccaMelhuish I did copy the style data from the figma and this is how it looks. To keep things responsive and using the options given by Elementor, this is the best so far, keeping the layouts in check. I will try to push the button float to bottom so both button remains equal. 

@BeccaMelhuish updated! please check :)

**Comment by BeccaMelhuish** [comment]
Thank you @devosama1!
