### ISSUE TITLE
BUG: Help Centre website still feeding through to the platform version 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#481]
@devosama1, as per Kevin's Slack message, the website header and footer is feeding through to the platform version of the HC, at 'Level 2' (not the homepage) and even after cache has been cleared:

![image](https://github.com/citizenos/citizenos-web/assets/61320526/627f7720-e02f-461b-a97a-8cb54f9ce31c)

**Comment by devosama1** [comment]
@BeccaMelhuish resolved
