### ISSUE TITLE
TASK: Fix DDA funding logos

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#485]
**What needs to be done?**
On https://citizenos.com/projects/dda/ the Active Citizens Fund logo is blurry. Also the order of the logos has shifted. Please see screenshot for the correct order.

<img width="1011" alt="Screenshot 2023-09-28 at 14 24 18" src="https://github.com/citizenos/citizenos-web/assets/72747107/afef7d20-9151-4af1-83da-17944c090068">

**Location**
https://citizenos.com/projects/dda/

**Any additional files or info needed?**
I think @oksks you already have the logos? If not then please take it from here h[ttps://acf.ee/taotlusvoorud/logod-ja-visuaal
](url)

**Deadline**
Please fix it as soon as possible.

**Comment by oksks** [comment]
Done, though they're not fitting into one row now, but I think that's OK. Let me know if it isn't!
