### ISSUE TITLE
TASK: Update DDA Page

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#488]
**What needs to be done?**
Please change the following dates (screenshot attached) to

<img width="1390" alt="Screenshot 2023-10-12 at 10 57 51" src="https://github.com/citizenos/citizenos-web/assets/72747107/1d9ebd71-5557-47ab-af2d-4b932d08df81">

- Wednesday, 4 October | Project Results. Understanding what to assess and evaluate.
- Wednesday, 18 October | Project Impact. Using the Theory of Change to assess the impact of projects.
- Wednesday, 1 November | Reflections. Sharing overall experience.
- Wednesday, 15 November | Final presentations and voting for the best project.
- Thursday, 30 November | Democracy Defenders Network Launch 

**Location**
https://citizenos.com/projects/dda/ #programme

**Any additional files or info needed?**
@anettlinno hope this is an accurate summary of the sessions during the Impact Phase

**Deadline**
By Monday 16.10.23 if possible.

**Comment by oksks** [comment]
Done :)
