### ISSUE TITLE
TASK: Update Democracy Defenders Accelerator page

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#489]
**What needs to be done?**
Please change these dates to 4 October - 15 November. Online (see screenshot)

<img width="1398" alt="Screenshot 2023-10-12 at 10 57 33" src="https://github.com/citizenos/citizenos-web/assets/72747107/a0555baa-fbbf-48ae-a944-b8414558583b">

**Location**
https://citizenos.com/projects/dda/

**Any additional files or info needed?**
No

**Deadline**
By Monday 16.10.23 if possible

**Comment by oksks** [comment]
Done :) https://citizenos.com/projects/dda/
