### ISSUE TITLE
TASK: Update Democracy Defenders Accelerator Page

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#495]
**What needs to be done?**
1._Under Introduction Section_
1.Replace "Democracy is in danger, and urgently needs people to defend it.
Our 10-month civic leadership programme for young activists will help fight the democratic decline."

WITH "Democracy is in danger, and urgently needs people to defend it.
Our 10-month civic leadership programme, which ended on November 15th 2023 is helping young activists to fight the democratic decline".

_2. Hide "Programme tab"_

_3. Hide "Application tab"_

_4. Add tab "Project Results". Under project results please add the following copy..._

[Heading] Projects initiated as part of the DDA programme

[Paragraph] Democracy Defenders Accelerator (DDA) was our hands-on programme for civic activists across the world. The participants learned how to design and deliver civic engagement projects and practise participatory leadership skills — through both the running of real-life projects and working on project ideas. The entire ten-month learning process was supported by mentors and facilitators. As a result, 30 young people completed the programme, 17 project concepts were developed and 11 of these initiatives were piloted with real actions during the programme itself 

[bold]Here is a short overview of all the projects that went into action![bold] [Paragraph]

[Subheading] Syscraft [/Subheading]
[paragraph]An international team based in Canada, Montenegro, Argentina and the Netherlands developed a concept and [prototype](https://www.figma.com/proto/YCDfR9DemHu2kPHzjG59s0/Syscraft?node-id=159-5333&starting-point-node-id=159%3A5333&locale=en&scaling=scale-down-width) for making complex systems easier to understand. The main objective is to make systems change happen more effectively by fostering greater alignment and collaboration between partners and stakeholders. 

[bold]Team members:[/bold] Andee Pittman, Guillermo Martin Croppi, Marijana Sundic and Mathieu Akko Muus.[/paragraph]

[Subheading] Harvesting hope: Europe’s fight for food security[/Subheading]
[Paragraph] A European peer-to-peer initiative to raise awareness about the use of chemicals in agriculture and demand that decision makers in Europe put a stop to the use of harmful chemicals. The project utilises social media and direct networks, and it gives ideas and resources to individuals about how they can be actively involved. 

[bold]Team lead:[/bold] Onyx/Dimitrios Karagiannidis

[Subheading] Nature and the woman marginalised: A case study from Cameroon [/Subheading]

[paragraph] As part of this project, gatherings and a workshop were organised to engage women in Cameroon to discuss the problems of climate change. The project is founded on the principle that there can be no climate justice without gender justice. The initiative tries to tackle the problem of women’s equality in Cameroon, as they are currently not equally represented in decision making regarding climate change. 

[bold]Team lead: Ngangjoh Memunatu Riyuh [bold] 
[/paragraph]

[Subheading] E-Ranger [/Subheading]

[paragraph] 

This initiative is a programme in Indonesia which aims to raise awareness of the importance of internet privacy among school students. The team members work as teachers and have developed tools, led workshops and are planning to develop a curriculum to address these important topics in the school setting.

[bold]Team lead:[/bold] Sam Michael Nugraha Situmorang

[/paragraph]

[Subheading] Accessibility for Pwds [/Subheading]

With this project, the team has set a goal to improve access to public transportation in Indonesian cities for people with disabilities. This initiative aims, based on research and data, to raise awareness among decision-makers and the wider public in order to make public transportation-related decisions in an inclusive and engaging way. Access to public institutions and freedom to move is seen as a democratic right. Decisions regarding such important issues must be made inclusively.

[bold]Team:[/bold] Luthfy Ramiz, Syifa Annisa and Gio Pradipta

[/paragraph]

[Subheading] Enhancing women’s civic and political engagement via digital technology [/Subheading]

[paragraph]A project initiated in Mexico to increase the role of women as community leaders and make their voices heard more. The project identified women in local communities who are active and initiate change all the time, without realising that they are leaders and without being given the necessary recognition. During the project, workshops and discussions were held to exchange practices and experiences and learn about digital tools to improve civic participation.

[bold]Team:[/bold] Mar Marín and her local team [/paragraph]

[Subheading] Integration and trauma recovery among Afghan refugee women after migration in Italy [/Subheading] 

[paragraph] 

This project was developed to provide support for women who have suffered due to the war in Afghanistan and are living as refugees in Italy. As part of the project, a women’s group was established and a workshop was conducted to help them to integrate in Italy, learn about the new culture and support their trauma healing. Additionally, the project also aims to raise more awareness about the inclusion of Afghan women in Italy.

[/paragraph]

[Subheading] RED (Raise, Empower, Disseminate) for the youth [/Subheading] 

[paragraph] 
This project in Albania aimed to tackle low community participation due to the lack of a dedicated budget for young people in Kodovjat, in central Albania, with a large population of 3,500 inhabitants (Census 2011). With this initiative, the project team aims to motivate, empower and strengthen the voice of young people by creating a calendar of activities for youth which combines democracy, culture and capacity building.

[bold]Team:[/bold] Nensi Dragoti and his local team

[/paragraph]

[Subheading] ASEAN Youth Week – an ASEAN Youth Advocates Network project [/Subheading] 

[paragraph] 

The initiative in the Philippines provides civic engagement training for young people in Southeast Asia. The project provides a platform where young people can upgrade their skills in advocating youth issues in the government through networks such as the ASEAN secretariat, United Nations, etc. They provide online and hybrid training for young people in the Southeast Asia network where 600 young people are involved. 

[/paragraph]

[Subheading]Democracy literacy for students  [/Subheading] 

[paragraph]This project is initiated by educator Uswatun Hasanah (aka Anna) who realised that there is a pressing lack of political, democratic, digital and media literacy in society. She went on to design a project together with the students and engaged 25 active young people. They organised a discussion forum and capacity building sessions in school and connected the students with experts on matters of democracy and media. Anna also brought together her students to join the [Indonesian Opinion Festival](https://citizenos.com/news/indonesian-opinion-festival-gathered-4000-people/) as a committee team, and she gave them the floor as student representatives to speak up about democracy issues in Indonesia.

[bold]Team:[/bold] Uswatun Hasanah and her students in Central Java, Indonesia

[/paragraph]

[Subheading] Conduct critical research  for evidence-based policy-making  in Sri Lanka [/Subheading] 

[paragraph]
This project aims to improve the overall quality of democracy in Sri Lanka by building the capacity of civil society to conduct critical research and better engage with their legislators. Through discussions and focus groups with key stakeholders, the project is mapping how local government policies affect the community.

[bold]Team:[/bold] Pathirannehelage Lakshita Prasad and his external team [/paragraph]

[/paragraph]

[Subheading]Additional project ideas developed[/Subheading]

[pargraph]Additionally, six more project ideas were developed, which by the time of the programme did not result in piloted activities. However, the project teams had been working on their ideas, involved target groups and completed all the steps as part of the DDA programme. We hope these ideas come to fruition at a later date![/paragraph]

[bold]Youth brain drain in Albania.[/bold] A project idea tackling the major problem of young people leaving the country. Team: Brunilda Brati
[bold]Digital literacy for youth in North Sulawesi.[/bold] A project concept aiming to improve digital literacy among young people. 
[bold]Overall quality of democracy in Germany.[/bold] A concept with the aim of reducing radicalisation and polarisation. Team: Lukas Crombach, Nadya Melati (quit), Rangga A. Akhli, Nensi Dragoti
[bold]Deja Vu Cycles/Misassessment of processes by society.[/bold] The project idea tackles the challenge of spreading disinformation in Georgia.Team: Smaranda Olariu, Nato Gogrichiani 
[bold]Engaging youth to address human rights violations.[/bold] A project idea that has worked on ways to raise awareness about physical and sexual violence against women and help women to speak out about their experiences. Team: Gabriela Sulkaj, Erta Allamani, Neysa Thifal Aurellia Basista)
[bold]Personal privacy awareness in universities.[/bold] The idea has explored ways to raise awareness about and develop skills for personal data privacy among university students. Team: Sholahuddin Al-Fatih[/paragraph] 

[Heading] Key Learning [/Heading]

[paragraph]Based on the feedback and analysis, the participants admitted that they now feel more empowered to tackle complex problems, maintain a clear focus and approach the project in a way that avoids a loss of motivation and burnout. Here are the four key learning outcomes expressed by the participants.[paragraph]

[bold]Key learning 1:[/bold] Imagination towards what democracy could be

[bold]Key learning 2:[/bold] Breaking “wicked problems”

[bold]Key learning 3:[/bold] Learning to tackle projects in phases and plan achievable steps

[bold]Key learning 4:[/bold] Using critical thinking

_5. Add tab "Democracy Defenders Network". Under Democracy Defenders Network please add the following copy..._

[Subheading]Impact[/Subheading]

[paragraph] As a result of the ten-month programme, the participants together with Citizen OS initiated the Democracy Defenders Network – a participatory network for Citizen OS partners, alumni and like-minded activists to increase the capacity of civil society leaders and improve international cooperation.

The network is open for activists and organisations to exchange knowledge and coordinate initiatives together. The network applications are open and accepting new members is on a roll-up basis. The network is non-profit and there are no membership fees. [/paragraph]

[button] -> Learn more about the Democracy Defenders Network here! link: https://citizenos.com/news/join-the-democracy-defenders-network/ [/button]

[button] -> Apply to become a member of the project! link: https://docs.google.com/forms/d/e/1FAIpQLSf6p_jHHRZF1XSDCLB5Vv65TFTnaoeCAHZ6c6900yJ-yjBwiQ/alreadyresponded[/button]

**Location**
https://citizenos.com/projects/dda/

**Any additional files or info needed?**
@oksks for style reference for "Under project results please add the following copy...till the last paragraph about the Civic Initiative projects, I have sent a file for reference.

@oksks for Democracy Defenders Network this reference can help with the buttons (screenshot1)

<img width="1174" alt="Screenshot 2024-02-13 at 14 19 04" src="https://github.com/citizenos/citizenos-web/assets/72747107/27daf7a6-c7b7-4df1-bdce-dfd66d531953">

**Deadline**
Wednesday, 14th November 2024.

**Comment by oksks** [comment]
Doneeeee 😻
The only issue is with two buttons showing up on every tab. Can hide from everywhere or leave everywhere.
