### ISSUE TITLE
TASK: Change header date

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#496]
**What needs to be done?**
1.Change "20 Jan - 17 Nov 2023" to "20 Jan 2023 - 14 Jan 2024"
2.Change "40 participants" to "30 graduates"

**Location**
https://citizenos.com/projects/dda/

**Any additional files or info needed?**
<img width="724" alt="Screenshot 2024-02-13 at 18 37 48" src="https://github.com/citizenos/citizenos-web/assets/72747107/585c39ea-493c-42ff-8f22-a50465f05726">

**Deadline**
Wednesday, February 14, 2024

**Comment by oksks** [comment]
Done 🌸
