### ISSUE TITLE
TASK: Change side column text

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#497]
**What needs to be done?**
1.In the side column change "20 Jan – 17 Nov 2023" to "20 Jan – 15 Nov 2023" 

**Location**
https://citizenos.com/projects/dda/

**Any additional files or info needed?**
<img width="494" alt="Screenshot 2024-02-13 at 18 05 44" src="https://github.com/citizenos/citizenos-web/assets/72747107/aed9d76d-b18e-4eec-9efa-5240ab34ad2e">

**Deadline**
Wednesday, February 14th

**Comment by oksks** [comment]
Done 🥳
