### ISSUE TITLE
TASK: DDA introduction text changes 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#498]
**What needs to be done?**
1.Change "participants will learn" to "participants learnt" (see screenshot)

<img width="816" alt="Screenshot 2024-02-13 at 18 23 02" src="https://github.com/citizenos/citizenos-web/assets/72747107/9b400b7e-3bcc-43d4-8f90-6ee70a4ce976">

**Location**
https://citizenos.com/projects/dda/

**Any additional files or info needed?**
Add designs, copy, screenshots etc - anything required to get on with the task

**Deadline**
Wednesday, February 14 2024

**Comment by oksks** [comment]
Done ✅
