### ISSUE TITLE
TASK: DDA introduction changes 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#499]
**What needs to be done?**
1. Change "Who is the DDA for?" to "Who Was the DDA for?"
2. Change the "DDA is aimed" to "DDA was aimed"
3. Change "What will it cost?" to "What did it cost?"
4. Change "How to apply" to "Application process"
5. Change "Willing participants apply" to "willing participants applied"

**Location**
https://citizenos.com/projects/dda/

**Any additional files or info needed?**
<img width="906" alt="Screenshot 2024-02-13 at 18 21 39" src="https://github.com/citizenos/citizenos-web/assets/72747107/c85d2145-2614-4e1f-9b7f-8916d062cc73">

**Deadline**
Wednesday, February 14 2024

**Comment by oksks** [comment]
Also done 🌟
