### ISSUE TITLE
TASK: DDA introduction text

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#500]
**What needs to be done?**
1. Change "The DDA consists" to "The DDA consisted of"
2. Change from "20 January - 17 November 2023" to "20 January - 15 November 2023"

**Location**
https://citizenos.com/projects/dda/

**Any additional files or info needed?**
<img width="909" alt="Screenshot 2024-02-13 at 18 21 12" src="https://github.com/citizenos/citizenos-web/assets/72747107/a5218c4f-1d04-4f77-8c67-f7940629b92d">

**Deadline**
Wednesday, February 14 2024

**Comment by oksks** [comment]
Done 🥰
