### ISSUE TITLE
TASK: Remove further information

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#501]
**What needs to be done?**
1. Remove the section "Further information"

**Location**
https://citizenos.com/projects/dda/

**Any additional files or info needed?**
<img width="1235" alt="Screenshot 2024-02-13 at 18 45 48" src="https://github.com/citizenos/citizenos-web/assets/72747107/60dee1fa-1512-4c3c-b88d-b9ce8859278f">

**Deadline**
Wednesday, November 14 2024

**Comment by oksks** [comment]
Done 🤗
