### ISSUE TITLE
TASK: Change Project status and dates

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#502]
**What needs to be done?**
1. Change the status from "Ongoing" to "Past"
2. Change dates from "20.01.2023 - 17.11.2023" to 20.01.2023 - 15.11.2023

**Location**
https://citizenos.com/projects/

**Any additional files or info needed?**
@oksks do you know why this image is rounded? 

<img width="1227" alt="Screenshot 2024-02-13 at 18 50 42" src="https://github.com/citizenos/citizenos-web/assets/72747107/655a4dfe-6486-4216-ba34-e0100ac8cdd9">

**Deadline**
Wednesday, February 14, 2024

**Comment by oksks** [comment]
It's just what we have :D If you know where to get a non-rounded one, I'll replace it!
![Screenshot 2024-02-13 at 22 15 07](https://github.com/citizenos/citizenos-web/assets/34126353/7d1e2fb3-9f2b-4ddc-b965-27b19541963e)

Done!

**Comment by oksks** [comment]
The image now also has the wrong date on it!
