### ISSUE TITLE
TASK: Key learning changes

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#503]
**What needs to be done?**
1. Change "Key learning" to "Key learning outcomes"
2. Upgrade the text to include a short description

Key learning 1: Imagination towards what democracy could be 

The participants indicated that their imagination was piqued in terms of what democracy could become.

Key learning 2: Breaking “wicked problems”

According to the survey, the participants expressed that complex and “wicked” problems became less daunting because the programme taught to break them into smaller problems in a systematic way.

Key learning 3: Learning to tackle projects in phases and plan achievable steps 

The participants emphasised that the Democracy Defenders Accelerator programme helped them to break down the project into phases, with milestones that were actually achievable.

Key learning 4: Using critical thinking 

Another important learning outcome for the participants was the use of critical thinking when reaching out to stakeholders.

**Location**
https://citizenos.com/news/30-young-activists-are-now-trained-democracy-defenders/

**Any additional files or info needed?**
<img width="890" alt="Screenshot 2024-02-13 at 19 05 35" src="https://github.com/citizenos/citizenos-web/assets/72747107/8184dc70-a5ab-48e1-a0e8-536f9968d149">

@oksks  it could look something like this, but I have shortened the text (see screenshot).
<img width="1186" alt="Screenshot 2024-02-13 at 19 10 05" src="https://github.com/citizenos/citizenos-web/assets/72747107/c7e1c002-c6af-401a-b6ba-7a1d0caa794d">

**Deadline**
Wednesday, February 14, 2024

**Comment by oksks** [comment]
Done @ssin1901 ✨
