### ISSUE TITLE
TASK: One more date correction 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#506]
**What needs to be done?**
@oksks million apologies but it just came to my mind that the project date over here should match what's in the header. Can we change it from "20.01.2023 - 15.11.2023" to "20.01.2023 - 14.01.2024"? 

**Location**
https://citizenos.com/projects

**Any additional files or info needed?**
<img width="1368" alt="Screenshot 2024-02-13 at 22 37 33" src="https://github.com/citizenos/citizenos-web/assets/72747107/f2664b79-fee4-42f8-9111-2ab01815eba1">

**Deadline**
ASAP

**Comment by oksks** [comment]
Done! ✨
