### ISSUE TITLE
TASK: Update Team page

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-web#507]
**What needs to be done?**
1. Please remove Anett's info and add Margo as the first contact in the column
2. Please adapt Margo's role in the organisation as follows: CEO, Co-Founder & Technology Evangelist
3. Please remove Kati's info on the site
3. Please adapt photos of other team members who attended the most recent photoshoot (https://drive.google.com/drive/u/0/folders/1Msx2uAXykNV9c2w4gDVH3fpiMiavi025)

**Location**
https://citizenos.com/team

**Deadline**
@oksks please do this in the nearest opportunity but no later than 27th of February.

**Comment by oksks** [comment]
Done! :)
