### ISSUE TITLE
TASK: Update text in the contact page

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-web#508]
**What needs to be done?**
1. Please adapt the text related to HQ going fully remote. Please adapt the text as follows:

Citizen OS hosts a fully remote headquarters alongside an office in Jakarta, Indonesia. Both offices are autonomous entities operating under the same brand and united by a shared mission and vision. This emphasises Citizen OS's dedication to leveraging technology for collaboration and engagement regardless of physical location.

2. Please remove the title "Estonian office" and rename it "Legal information"

3. Please change the photo of "Estonian office" to this one: https://drive.google.com/file/d/1sLfS51frmxXZ9FOpUQosPO68fzL2fxiR/view?usp=sharing

4. Please adapt the Indonesian team photo to this: https://drive.google.com/file/d/1d1Dngr2EMl347VxKJtIi4uyFsm-EZAYJ/view?usp=sharing

**Location**
https://citizenos.com/contact/

**Deadline**
@oksks please do this by 01.03.2024 but also not much sooner (we still have the office till the end of the month ;)

**Comment by oksks** [comment]
Done! https://citizenos.com/contact/ @MeelikaH
