### ISSUE TITLE
TASK: Adding a new on-going project to the Projects page

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-web#509]
**What needs to be done?**
We have a new project on-going: Erasmus Mundus Joint Master’s Programme, “Artificial Intelligence for Sustainable Societies” (AISS) which would need to be added to the Projects as an ongoing project.

**Location**
https://citizenos.com/projects/

**Any additional files or info needed?**
Photo: https://drive.google.com/file/d/1y8HCAPxls2mVC4EMHXm7LLwXorMty8xM/view?usp=share_link if this will not visually work well because of the text, please use this: https://unsplash.com/photos/a-woman-freelancer-working-on-laptop-sitting-on-a-pier-by-the-backyard-lake-a-concept-of-remote-office-work-during-vacation-yOuZaN3zqXc or this: https://unsplash.com/photos/three-people-sitting-in-front-of-table-laughing-together-g1Kr4Ozfoac

Text: https://docs.google.com/document/d/1L-va8PjCnGix3VU9XFR_USshZrDVT5Vvn4F5QgpmGjA/edit?usp=sharing

**Deadline**
@oksks if possible, by 4.03.2024

**Comment by oksks** [comment]
Published in March, forgot to close ticket
