### ISSUE TITLE
TASK: Hide Help Centre 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#512]
**What needs to be done?**
Help centre page should be temporarily hidden (

Also removed from here (see screenshot) and any other places that I might have missed. @BeccaMelhuish hope this is alright.

**Location**
https://citizenos.com/help

**Any additional files or info needed?**
<img width="1436" alt="Screenshot 2024-03-13 at 17 28 39" src="https://github.com/citizenos/citizenos-web/assets/72747107/4ee7c471-221f-49c8-bfb9-c445adeb56d0">

**Deadline**
@oksks on Monday 18th March, when Redesign is launched

**Comment by oksks** [comment]
Done - hid in the footer + hid the /help section - and though articles are still up, they aren't accessible through the site anymore, only via a direct link.
