### ISSUE TITLE
TASK: Redirect Non-www

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#513]
**What needs to be done?**
@oksks it came to my attention that we MAY need to redirect www.citizenos.com to https://citizenos.com

A lot of users accidentally type www.citizenos.com and get a Not Found error

**Location**
https://citizenos.com

**Any additional files or info needed?**
This article might have more information about what I mean https://www.hostinger.com/tutorials/how-to-redirect-non-www-urls-to-www

**Deadline**
Depends on how easy it is to do. Maybe needs to happen on a web maintenance day. The main reason why it is important to do it quickly is that www.citizenos.com has been communicated in many places.

**Comment by ssin1901** [comment]
@ilmartyrk looping you in as well for app.citizenos.com

**Comment by oksks** [comment]
This needs a developer to install a redirect plugin :( The free and good one seems to be https://wordpress.org/plugins/redirection/. @ilmartyrk is this something you could help with? As we don't have a web developer yet, and the discussion with Margo about the maintenance budget is yet to happen.

**Comment by ilmartyrk** [comment]
@oksks @ssin1901 I can help, but don't think that the plugin will work, seems to be related to hosting, will check what can be done

**Comment by ilmartyrk** [comment]
@oksks @ssin1901 should be fixed

**Comment by ssin1901** [comment]
Thanks a million @ilmartyrk looks really awesome! @oksks I think we can close the issue.
