### ISSUE TITLE
BUG: Main menu design broken (high priority)

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-web#515]
**Describe the bug**
On https://citizenos.com/ the main menu design is broken (screenshot1)
<img width="1373" alt="Screenshot 2024-05-30 at 15 10 45" src="https://github.com/citizenos/citizenos-web/assets/72747107/531df23f-5b0c-4594-bbc7-071822e83399">

**How critical is the bug?**
Visually bad, but the items still work. I would still say high-priority @oksks 

**To Reproduce**
1. Go to https://citizenos.com

**Expected behavior**
Navigation items should be displayed inline without bullet points. Hamburger menu should only appear on a smaller screens and in that case the items should be hidden.

@oksks basically it should go back to how it was.

**Screenshots**
<img width="1373" alt="Screenshot 2024-05-30 at 15 10 45" src="https://github.com/citizenos/citizenos-web/assets/72747107/531df23f-5b0c-4594-bbc7-071822e83399">

**Desktop (please complete the following information):**
 - Mac OS Google Chrome and Safari
  
**Smartphone (please complete the following information):**
 
**Additional context**

**Comment by ilmartyrk** [comment]
@ssin1901 @oksks fixed
